(function(){function h(a){throw a;}var j=void 0,l=!0,m=null,n=!1;function aa(a){return function(){return a}}var p,ba=ba||{},ca=this;function da(){}
function r(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return a!==j}function fa(a){return"array"==r(a)}function w(a){var b=r(a);return"array"==b||"object"==b&&"number"==typeof a.length}function x(a){return"string"==typeof a}function ha(a){return"boolean"==typeof a}function ja(a){return"number"==typeof a}function ka(a){return"function"==r(a)}function la(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}var ma="closure_uid_"+(1E9*Math.random()>>>0),oa=0;
function y(a,b){var c=a.split("."),d=ca;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&t(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function pa(a,b){function c(){}c.prototype=b.prototype;a.zb=b.prototype;a.prototype=new c;a.prototype.constructor=a};var z=Array.prototype,qa=z.indexOf?function(a,b,c){return z.indexOf.call(a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a.length+c):c;if(x(a))return!x(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ra=z.forEach?function(a,b,c){z.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=x(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},sa=z.filter?function(a,b,c){return z.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=x(a)?
a.split(""):a,k=0;k<d;k++)if(k in g){var q=g[k];b.call(c,q,k,a)&&(e[f++]=q)}return e},ta=z.map?function(a,b,c){return z.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=x(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};function va(a,b){var c=qa(a,b);0<=c&&z.splice.call(a,c,1)}function wa(a){return z.concat.apply(z,arguments)}function xa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function ya(a,b,c){return 2>=arguments.length?z.slice.call(a,b):z.slice.call(a,b,c)}function za(a,b,c){if(!w(a)||!w(b)||a.length!=b.length)return n;var d=a.length;c=c||Aa;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return n;return l}function Ba(a,b){return a>b?1:a<b?-1:0}function Aa(a,b){return a===b}function Ca(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}};var A="StopIteration"in ca?ca.StopIteration:Error("StopIteration");function B(){}B.prototype.next=function(){h(A)};B.prototype.u=function(){return this};function E(a){if(a instanceof B)return a;if("function"==typeof a.u)return a.u(n);if(w(a)){var b=0,c=new B;c.next=function(){for(;;){b>=a.length&&h(A);if(b in a)return a[b++];b++}};return c}h(Error("Not implemented"))}function F(a,b,c){if(w(a))try{ra(a,b,c)}catch(d){d!==A&&h(d)}else{a=E(a);try{for(;;)b.call(c,a.next(),j,a)}catch(e){e!==A&&h(e)}}}
function Ea(a,b,c){var d=E(a);a=new B;a.next=function(){for(;;){var a=d.next();if(b.call(c,a,j,d))return a}};return a}function G(a,b,c){var d=E(a);a=new B;a.next=function(){for(;;){var a=d.next();return b.call(c,a,j,d)}};return a}function Fa(a,b,c){var d=c;F(a,function(a){d=b.call(j,d,a)});return d}function Ka(a){var b=arguments,c=b.length,d=0,e=new B;e.next=function(){try{return d>=c&&h(A),E(b[d]).next()}catch(a){return(a!==A||d>=c)&&h(a),d++,this.next()}};return e}
function H(a){if(w(a))return xa(a);a=E(a);var b=[];F(a,function(a){b.push(a)});return b}function La(a,b){try{return E(a).next()}catch(c){return c!=A&&h(c),b}};function Ma(){}Ma.ya=function(){return Ma.Aa?Ma.Aa:Ma.Aa=new Ma};Ma.prototype.Ua=0;Ma.ya();var Na={};function Oa(a){if(!w(a))return n;for(var b=0,c=a.length;b<c;b++)if(window.isNaN(a[b]))return n;return l}y("jsnx.utils.is_list_of_ints",Oa);y("jsnx.utils.cumulative_sum",function(a){var b=0;return G(a,function(a){return b+=a})});y("jsnx.utils.generate_unique_node",function(){return":"+(Ma.ya().Ua++).toString(36)});function I(a,b){for(var c in a)b.call(j,a[c],c,a)}function Pa(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d}function Qa(a){var b=0,c;for(c in a)b++;return b}function L(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function M(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Ra(a){for(var b in a)delete a[b]}function Va(a){"__d3datum__"in a&&delete a.__d3datum__}function O(a,b,c){return b in a?a[b]:c}function Wa(a){var b={},c;for(c in a)b[c]=a[c];return b}var Xa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function P(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Xa.length;f++)c=Xa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Ya(a){return a instanceof B||ka(a.u)}function Za(a){if(x(a)||w(a)||"length"in a)return a.length;if($a(a))return Qa(a);h(new TypeError)}function Q(a,b,c,d){ha(c)&&(d=c,c=m);if(d){var e=b;b=function(a){e.apply(this,a)}}Ya(a)?F(a,b,c):w(a)||x(a)?ra(a,b,c):la(a)&&Q(M(a),b,c)}y("jsnx.forEach",Q);function ab(a,b){if(w(a))return ta(a,b,j);if(Ya(a))return G(a,b,j);if(la(a))return Pa(a,b,j);h(new TypeError)}
function bb(){var a=arguments,b=a[0];if(w(b))return Ca.apply(m,a);if(Ya(b)){var b=new B,c=a.length;b.next=function(){for(var b=[],e=0;e<c;e++)b.push(a[e].next());return b};return b}if(la(b))return Ca.apply(m,ta(a,M));h(new TypeError)}
function cb(a,b,c){if(0===arguments.length)return[];1===arguments.length?(b=a,a=0,c=1):2===arguments.length?c=1:3===arguments.length&&0===arguments[2]&&h("range() step argument must not be zero");var d=new B,e=0>c,f=a,g;d.next=function(){(e&&f<=b||!e&&f>=b)&&h(A);g=f;f+=c;return g};return d}
function db(a){var b=eb(a),c=b.length;if(2>c)return new B;var d=eb(cb(2));a=new B;a.next=function(){var a=ta(d,function(a){return b[a]});this.next=function(){var a=n,e;for(e=2;e--;)if(d[e]!=e+c-2){a=l;break}a||h(A);d[e]+=1;for(a=e+1;2>a;a++)d[a]=d[a-1]+1;return ta(d,function(a){return b[a]})};return a};return a}
function fb(a){var b=eb(a),c=b.length,d=ja(2)?2:c;if(d>c)return new B;var e=eb(cb(c)),f=eb(cb(c,c-d,-1));a=new B;var g=new B,k,q=l;a.next=function(){this.next=k.next;return ta(e.slice(0,d),function(a){return b[a]})};g.next=function(){return q};k=gb(g,function(a){a||h(A);q=n;return cb(d-1,-1,-1)},function(a){if(!q)if(f[a]-=1,0===f[a])e.splice.apply(e,[a,e.length].concat(e.slice(a+1).concat([e[a]]))),f[a]=c-a;else{var k=f[a],g=e[a];e[a]=e[e.length-k];e[e.length-k]=g;q=l;return hb([ta(e.slice(0,d),function(a){return b[a]})])}},
function(a){return a});return a}function ib(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)!t(a[c])||"object"!==r(a[c])?a[c]=R(d[c]):"object"===r(a[c])&&"object"===r(d)&&ib(a[c],d[c]);for(var f=0;f<Xa.length;f++)c=Xa[f],Object.prototype.hasOwnProperty.call(d,c)&&(!t(a[c])||"object"!==r(a[c])?a[c]=R(d[c]):"object"===r(a[c])&&"object"===r(d)&&ib(a[c],d[c]))}}function eb(a){if(w(a))return xa(a);if(Ya(a))return H(a);if(la(a))return M(a);h(new TypeError)}y("jsnx.toArray",eb);
function pb(a){var b=new B,c=E(M(a));b.next=function(){var b=c.next();return[b,a[b]]};return b}function hb(a){"object"===r(a)&&(!w(a)&&!Ya(a))&&(a=M(a));return E(a)}
function gb(a){var b=new B,c=ya(arguments,1);if(0===c.length)return a;try{a=E(a)}catch(d){return b.next=function(){"Not implemented"===d.message&&h(new TypeError)},b}var e=m;b.next=function(){var d,g;try{for(;!t(d);)d=e.next()}catch(k){for(;!t(g)||!t(d);)g=a.next(),d=c[0](g);if(Ya(d))return e=gb.apply(m,wa([d],ya(c,1))),b.next();e=m}return d};return b}y("jsnx.sentinelIterator",function(a,b){var c=new B;c.next=function(){return La(a,b)};return c});
function $a(a){var b=Object.prototype.hasOwnProperty;if(!a||"object"!==r(a)||a.nodeType||a==a.window)return n;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return n}catch(c){return n}for(var d in a);return d===j||b.call(a,d)}
function R(a,b){b=b||[];var c=r(a);if("object"==c&&$a(a)||"array"==c){var d;d=b;var e;a:{e=function(b){return a===b[0]};for(var f=d.length,g=x(d)?d.split(""):d,k=0;k<f;k++)if(k in g&&e.call(j,g[k])){e=k;break a}e=-1}d=0>e?m:x(d)?d.charAt(e):d[e];if(d!==m)return d[1];if(a.$)return d=[a,a.$()],b.push(d),d[1];c="array"==c?[]:{};d=[a,c];b.push(d);for(var q in a)c[q]=R(a[q],b);return c}return a}
function qb(a){function b(){}var c={},d;b.prototype=a.constructor.prototype;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);c=R(c);a=new b;for(d in c)a[d]=c[d];return a};function rb(a){if("function"==typeof a.J)return a.J();if(x(a))return a.split("");if(w(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return L(a)};function sb(a,b){this.b={};this.p=[];var c=arguments.length;if(1<c){c%2&&h(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.N(a)}p=sb.prototype;p.n=0;p.H=0;p.c=function(){return this.n};p.J=function(){this.L();for(var a=[],b=0;b<this.p.length;b++)a.push(this.b[this.p[b]]);return a};p.fa=function(){this.L();return this.p.concat()};p.d=function(a){return tb(this.b,a)};p.ba=function(){return 0==this.n};
p.clear=function(){this.b={};this.H=this.n=this.p.length=0};p.remove=function(a){return tb(this.b,a)?(delete this.b[a],this.n--,this.H++,this.p.length>2*this.n&&this.L(),l):n};p.L=function(){if(this.n!=this.p.length){for(var a=0,b=0;a<this.p.length;){var c=this.p[a];tb(this.b,c)&&(this.p[b++]=c);a++}this.p.length=b}if(this.n!=this.p.length){for(var d={},b=a=0;a<this.p.length;)c=this.p[a],tb(d,c)||(this.p[b++]=c,d[c]=1),a++;this.p.length=b}};p.get=function(a,b){return tb(this.b,a)?this.b[a]:b};
p.set=function(a,b){tb(this.b,a)||(this.n++,this.p.push(a),this.H++);this.b[a]=b};p.N=function(a){var b;a instanceof sb?(b=a.fa(),a=a.J()):(b=M(a),a=L(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};p.$=function(){return new sb(this)};p.D=function(){return this.u(l)};p.aa=function(){return this.u(n)};
p.u=function(a){this.L();var b=0,c=this.p,d=this.b,e=this.H,f=this,g=new B;g.next=function(){for(;;){e!=f.H&&h(Error("The map has changed since the iterator was created"));b>=c.length&&h(A);var k=c[b++];return a?k:d[k]}};return g};function tb(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function S(a){this.b=new sb;a&&this.N(a)}function ub(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ma]||(a[ma]=++oa)):b.substr(0,1)+a}p=S.prototype;p.c=function(){return this.b.c()};p.add=function(a){this.b.set(ub(a),a)};p.N=function(a){a=rb(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};p.remove=function(a){return this.b.remove(ub(a))};p.clear=function(){this.b.clear()};p.ba=function(){return this.b.ba()};p.contains=function(a){return this.b.d(ub(a))};
function vb(a,b){for(var c=new S,d=rb(b),e=0;e<d.length;e++){var f=d[e];a.contains(f)&&c.add(f)}return c}function wb(a,b){for(var c=a.$(),d=rb(b),e=d.length,f=0;f<e;f++)c.remove(d[f]);return c}p.J=function(){return this.b.J()};p.$=function(){return new S(this)};p.u=function(){return this.b.u(n)};function xb(a){if(a!=m)try{a.clear()}catch(b){h(Error("Input graph is not a jsnx graph type"))}else a=new Na.Fa;return a}
function yb(a,b,c){var d;if(a.hasOwnProperty("adj"))try{return d=zb(a.adj,b,a.o()),"graph"in a&&"object"===r(a.graph)&&(d.graph=Wa(a.graph)),"node"in a&&"object"===r(a.node)&&(d.node=Pa(a.node,function(a){return Wa(a)})),d}catch(e){h(Error("Input is not a correct jsnx graph"))}if("object"===r(a))try{return zb(a,b,c)}catch(f){try{var g=xb(b);g.m(a);if(g.o()&&!g.h()){var k={};I(a,function(a,b){ra(a,function(a){a in k||g.v(b,a)});k[b]=1})}else{var q=[];I(a,function(a,b){ra(a,function(a){q.push([b,a])})});
g.e(q)}return g}catch(C){h(Error("Input is not known type."))}}if(w(a))try{var s=xb(b);s.e(a);return s}catch(D){h(Error("Input is not valid edge list"))}}y("jsnx.to_networkx_graph",yb);y("jsnx.convert_to_undirected",Na.ib);y("jsnx.convert_to_undirected",Na.hb);y("jsnx.to_dict_of_lists",Na.Ab);
function zb(a,b,c){var d=xb(b),e,f;d.m(a);c?d.h()?(d.o()?(e=[],I(a,function(a,b){w(a)&&h(Error());I(a,function(a,c){I(a,function(a,d){e.push([b,c,d,a])})})})):(e=[],I(a,function(a,b){w(a)&&h(Error());I(a,function(a,c){I(a,function(a){e.push([b,c,a])})})})),d.e(e)):d.o()?(f=new S,I(a,function(a,b){w(a)&&h(Error());I(a,function(a,c){f.contains([b,c].toString())||(e=[],I(a,function(a,d){e.push([b,c,d,a])}),d.e(e),f.add([c,b].toString()))})})):(f=new S,I(a,function(a,b){w(a)&&h(Error());I(a,function(a,
c){f.contains([b,c].toString())||(e=[],I(a,function(a){e.push([b,c,a])}),d.e(e),f.add([c,b].toString()))})})):d.o()&&!d.h()?(f=new S,I(a,function(a,b){w(a)&&h(Error());I(a,function(a,c){f.contains([b,c].toString())||(d.v(b,c,a),f.add([c,b].toString()))})})):(e=[],I(a,function(a,b){w(a)&&h(Error());I(a,function(a,c){e.push([b,c,a])})}),d.e(e));return d};function Ab(a){this.name="JSNetworkXException";this.message=a}Ab.prototype=Error();Ab.prototype.constructor=Ab;y("jsnx.JSNetworkXException",Ab);function T(a){Ab.call(this,a);this.name="JSNetworkXError"}pa(T,Ab);y("jsnx.JSNetworkXError",T);function Bb(a){Ab.call(this,a);this.name="JSNetworkXPointlessConcept"}pa(Bb,Ab);y("jsnx.JSNetworkXPointlessConcept",Bb);function Cb(a){Ab.call(this,a);this.name="JSNetworkXAlgorithmError"}pa(Cb,Ab);y("jsnx.JSNetworkXAlgorithmError",Cb);
function Db(a){Cb.call(this,a);this.name="JSNetworkXUnfeasible"}pa(Db,Cb);y("jsnx.JSNetworkXUnfeasible",Db);function Eb(a){Db.call(this,a);this.name="JSNetworkXNoPath"}pa(Eb,Db);y("jsnx.JSNetworkXNoPath",Eb);function Fb(a){Cb.call(this,a);this.name="JSNetworkXUnbounded"}pa(Fb,Cb);y("jsnx.JSNetworkXUnbounded",Fb);var V={tb:function(a){return Math.floor(Math.random()*a)},Cb:function(a,b){return a+Math.random()*(b-a)},fb:function(a,b,c){return Math.min(Math.max(a,b),c)},Ta:function(a,b){var c=a%b;return 0>c*b?c+b:c},qb:function(a,b,c){return a+c*(b-a)},sb:function(a,b,c){return Math.abs(a-b)<=(c||1E-6)},wa:function(a){return V.Ta(a,360)},Ea:function(a){return a*Math.PI/180},ab:function(a){return 180*a/Math.PI},cb:function(a,b){return b*Math.cos(V.Ea(a))},eb:function(a,b){return b*Math.sin(V.Ea(a))},xa:function(a,
b,c,d){return V.wa(V.ab(Math.atan2(d-b,c-a)))},bb:function(a,b){var c=V.wa(b)-V.wa(a);180<c?c-=360:-180>=c&&(c=360+c);return c},wb:function(a){return 0==a?0:0>a?-1:1},rb:function(a,b,c,d){c=c||function(a,b){return a==b};d=d||function(b){return a[b]};for(var e=a.length,f=b.length,g=[],k=0;k<e+1;k++)g[k]=[],g[k][0]=0;for(var q=0;q<f+1;q++)g[0][q]=0;for(k=1;k<=e;k++)for(q=1;q<=e;q++)g[k][q]=c(a[k-1],b[q-1])?g[k-1][q-1]+1:Math.max(g[k-1][q],g[k][q-1]);for(var C=[],k=e,q=f;0<k&&0<q;)c(a[k-1],b[q-1])?(C.unshift(d(k-
1,q-1)),k--,q--):g[k-1][q]>g[k][q-1]?k--:q--;return C},F:function(a){var b;b=arguments;var c=function(a,b){return a+b};if(b.reduce)b=b.reduce(c,0);else{var d=0;ra(b,function(a){d=c.call(j,d,a)});b=d}return b},Ma:function(a){return V.F.apply(m,arguments)/arguments.length},xb:function(a){var b=arguments.length;if(2>b)return 0;var c=V.Ma.apply(m,arguments),b=V.F.apply(m,ta(arguments,function(a){return Math.pow(a-c,2)}))/(b-1);return Math.sqrt(b)},ob:function(a){return isFinite(a)&&0==a%1},nb:function(a){return isFinite(a)&&
!isNaN(a)},vb:function(a,b){return Math.floor(a+(b||2E-15))},ub:function(a,b){return Math.ceil(a-(b||2E-15))}};function Hb(a){var b=[];Ib(new Jb,a,b);return b.join("")}function Jb(){this.ta=j}
function Ib(a,b,c){switch(typeof b){case "string":Kb(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if(fa(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],Ib(a,a.ta?a.ta.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),Kb(f,c),c.push(":"),
Ib(a,a.ta?a.ta.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:h(Error("Unknown type: "+typeof b))}}var Lb={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Mb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Kb(a,b){b.push('"',a.replace(Mb,function(a){if(a in Lb)return Lb[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Lb[a]=e+b.toString(16)}),'"')};var Nb={};y("jsnx.Map.Entry",function(a,b){this.key=a;this.value=b});function Ob(a){this.b={};this.k=[];this.ra={};a&&(this.ra.hash=a)}p=Ob.prototype;p.n=0;p.H=0;p.c=function(){return this.n};p.J=function(){this.L();for(var a=[],b=0;b<this.k.length;b++)a.push(this.b[this.k[b]][1]);return a};p.fa=function(){this.L();for(var a=[],b=0;b<this.k.length;b++)a.push(this.b[this.k[b]][0]);return a};p.d=function(a){var b=Pb(this,a);return Object.prototype.hasOwnProperty.call(obj,b)?this.b[b][0]===a:n};
p.ba=function(){return 0==this.n};p.clear=function(){this.b={};this.H=this.n=this.k.length=0};p.remove=function(a){a=Pb(this,a);return Object.prototype.hasOwnProperty.call(this.b,a)?(delete this.b[a],this.n--,this.H++,this.k.length>2*this.n&&this.L(),l):n};
p.L=function(){if(this.n!=this.k.length){for(var a=0,b=0;a<this.k.length;){var c=this.k[a];Object.prototype.hasOwnProperty.call(this.b,c)&&(this.k[b++]=c);a++}this.k.length=b}if(this.n!=this.k.length){for(var d={},b=a=0;a<this.k.length;)c=this.k[a],Object.prototype.hasOwnProperty.call(d,c)||(this.k[b++]=key,d[c]=1),a++;this.k.length=b}};
p.get=function(a,b){var c=Pb(this,val);return Object.prototype.hasOwnProperty.call(this.b,c)?(c=this.b[c],a!==c[0]&&h(Error("Provided key not equal to hashed key")),c[1]):b};p.set=function(a,b){var c=Pb(this,a);Object.prototype.hasOwnProperty.call(this.b,c)||(this.n++,this.k.push(c),this.H++);this.b[c]=[a,b]};p.N=function(a){var b;if(a instanceof Ob)b=a.fa(),a=a.J();else{if(a instanceof B){F(a,function(a){this.set(a[0],a[1])},this);return}b=M(a);a=L(a)}for(var c=0;c<b.length;c++)this.set(b[c],a[c])};
p.$=function(){return new Ob(this)};p.D=function(){return this.u(l)};p.aa=function(){return this.u(n)};function Qb(a){return a.u(2)}p.u=function(a){this.L();var b=0,c=this.k,d=this.b,e=this.H,f=this,g=new B;g.next=function(){for(;;){e!=f.H&&h(Error("The map has changed since the iterator was created"));b>=c.length&&h(A);var k=c[b++],k=d[k];return a?1==a?k[0]:k:k[1]}};return g};
function Pb(a,b){var c="";return c="hash"in a.ra?a.ra.hash(b):"hash"in b?"function"===typeof b.hash?b.hash():""+b.hash:"[object Object]"===Object.prototype.toString.call(b)?b[ma]||(b[ma]=++oa):""+b};function W(a,b){if(!(this instanceof W))return new W(a,b);this.i={};P(this.i,b||{});this.j=X(this);this.q=X(this);a!=m&&yb(a,this)}y("jsnx.classes.Graph",W);y("jsnx.Graph",W);W.__name__="Graph";W.prototype.i=m;W.prototype.q=m;W.prototype.Pa=function(){return this.i};W.prototype.graph=W.prototype.Pa;W.prototype.P=function(a){return this.j.get(a)};W.prototype.node=W.prototype.P;W.prototype.g=function(a){return 0<arguments.length?this.q:this.q.get(a)};W.prototype.adj=W.prototype.g;W.prototype.Na=W.prototype.g;
W.prototype.edge=W.prototype.Na;function X(a){return new Nb(a.i.hash)}W.prototype.name=function(a){if(t(a))this.i.name=a.toString();else return this.i.name||""};W.prototype.name=W.prototype.name;W.prototype.toString=function(){return this.name()};W.prototype.toString=W.prototype.toString;W.prototype.u=function(){return this.j.D()};W.prototype.__iterator__=W.prototype.u;W.prototype.t=function(a){this.a(a)||h({name:"KeyError",message:"Graph does not contain node "+a+"."});return this.g(a)};
W.prototype.get_node=W.prototype.t;W.prototype.Z=function(a,b){b!=m||(b={});"object"!==r(b)&&h(new T("The attr_dict argument must be an object."));this.ea(a,b)};W.prototype.add_node=W.prototype.Z;W.prototype.ea=function(a,b){this.a(a)?b&&P(this.P(a),b||{}):(this.q.set(a,X(this)),this.j.set(a,b||X(this)))};W.prototype.m=function(a,b){var c,d,e;b=b||{};Q(a,function(a){c=!this.a(a);fa(a)?(d=a[0],e=a[1],this.ea(d,P(Wa(b),e))):c?this.ea(a,Wa(b)):P(this.P(a),b)},this)};W.prototype.add_nodes_from=W.prototype.m;
W.prototype.sa=function(a){this.a(a)||h(new T("The node "+a+" is not in the graph"));this.Da(a)};W.prototype.remove_node=W.prototype.sa;W.prototype.Da=function(a){var b=this.W(a);this.j.remove(a);F(b,function(b){this.g(b).remove(a)});this.q.remove(a)};W.prototype.va=function(a){Q(a,this.Da,this)};W.prototype.remove_nodes_from=W.prototype.va;W.prototype.w=function(a){return a?Qb(this.j):this.j.D()};W.prototype.nodes_iter=W.prototype.w;W.prototype.nodes=function(a){return H(this.w(a))};
W.prototype.nodes=W.prototype.nodes;W.prototype.la=function(){return this.j.c()};W.prototype.number_of_nodes=W.prototype.la;W.prototype.Q=function(){return this.j.c()};W.prototype.order=W.prototype.Q;W.prototype.a=function(a){return!fa(a)&&this.j.d(a)};W.prototype.has_node=W.prototype.a;W.prototype.v=function(a,b,c){c=c||{};"object"!==r(c)&&h(new T("The attr_dict argument must be an object."));this.S(a,b,c)};W.prototype.add_edge=W.prototype.v;
W.prototype.S=function(a,b,c){this.O(a);this.O(b);var d=this.g(a),e={};d.d(b)?(e=d.get(b),P(e,c)):(P(e,c),this.g(a).set(b,e),this.g(b).set(a,e))};W.prototype.e=function(a,b){b=b||{};"object"!==r(b)&&h(new T("The attr_dict argument must be an object."));Q(a,function(a){var d=Za(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new T("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));a=Wa(b);P(a,g);this.S(e,f,a)},this)};W.prototype.add_edges_from=W.prototype.e;
W.prototype.Ka=function(a,b,c){c=c||{};x(b)||(c=b,b="weight");this.e(ab(a,function(a){var c={};c[b]=a[2];t(c[b])||h(new TypeError("Values must consist of three elements: "+Hb(a)));return[a[0],a[1],c]}),c)};W.prototype.add_weighted_edges_from=W.prototype.Ka;W.prototype.X=function(a,b){try{this.na(a,b)}catch(c){c instanceof TypeError&&h(new T("The edge "+a+"-"+b+" is not in the graph")),h(c)}};W.prototype.remove_edge=W.prototype.X;
W.prototype.na=function(a,b){this.a(a)&&this.a(b)&&(this.g(a).remove(b),a!=b&&this.g(b).remove(a))};W.prototype.M=function(a){Q(a,function(a){this.na(a[0],a[1])},this)};W.prototype.remove_edges_from=W.prototype.M;W.prototype.C=function(a,b){return this.a(a)&&this.a(b)&&this.g(a).d(b)};W.prototype.has_edge=W.prototype.C;W.prototype.V=function(a){return H(this.W(a))};W.prototype.neighbors=W.prototype.V;W.prototype.W=function(a){this.a(a)||h(new T("The node "+a+" is not in the graph."));return this.g(a).D()};
W.prototype.neighbors_iter=W.prototype.W;W.prototype.I=function(a,b){return H(this.f(a,b))};W.prototype.edges=W.prototype.I;W.prototype.f=function(a){ha(a)&&(a=m);return this.T(visitor,this.s(a))};W.prototype.edges_iter=W.prototype.f;W.prototype.T=function(a,b){var c=X(this),d=m;return gb(b,function(a){d=a[0];var b=new B,g=Qb(a[1]);b.next=function(){try{return g.next()}catch(a){a===A&&c.set(d,l),h(a)}};return b},function(b){if(!c.d(b[0]))return a(d,b)})};
W.prototype.ga=function(a,b,c){t(c)||(c=m);return this.a(a)?this.g(a).get(b,c):c};W.prototype.get_edge_data=W.prototype.ga;W.prototype.La=function(){return H(G(this.s(),function(a){return a[1].fa()}))};W.prototype.adjacency_list=W.prototype.La;function Rb(a,b){var c=m;b!=m?(!fa(b)&&!ba.pb(b)&&(b=[b]),c=G(hb(b),function(b){return[b,a.get(b)]})):c=Qb(a);return c}W.prototype.s=function(a){return Rb(this.q,a)};W.prototype.adjacency_iter=W.prototype.s;
W.prototype.A=function(a,b){if(this.a(a))return this.B(a,b).next()[1];var c=X(this);c.N(this.B(a,b));return c};W.prototype.degree=W.prototype.A;W.prototype.B=function(a,b){var c=this.s(a),d=Sb;b&&(d=jsnc.gb.Fa.yb);return G(c,function(a){var c=a[0];a=a[1];a=d(c,b)(0,a);return[c,a]})};W.prototype.degree_iter=W.prototype.B;W.prototype.clear=function(){this.name("");this.q.clear();this.j.clear();Ra(this.graph)};W.prototype.clear=W.prototype.clear;W.prototype.copy=function(){return qb(this)};
W.prototype.copy=W.prototype.copy;W.prototype.o=aa(n);W.prototype.is_multigraph=W.prototype.o;W.prototype.h=aa(n);W.prototype.is_directed=W.prototype.h;W.prototype.Y=function(){var a=new Y(m,this.i);a.m(G(this.w(l),function(a){return[a[0],R(a[1])]}));a.e(G(this.f(j,l),function(a){return[a[0],a[1],R(a[2])]}));return a};W.prototype.to_directed=W.prototype.Y;
W.prototype.pa=function(){var a=new W(m,this.i);a.m(G(this.w(l),function(a){return[a[0],R(a[1])]}));a.e(G(this.f(j,l),function(a){return[a[0],a[1],R(a[2])]}));return a};W.prototype.to_undirected=W.prototype.pa;W.prototype.R=function(a){a=this.K(a);var b=new this.constructor(m,this.i),c=b.j,d=b.q,e=this.q;F(a,function(a){var g=X(b);d.set(a,g);F(Qb(e.get(a)),function(b){c.d(u[0]);g.set(b[0],b[1]);d.get(b[0]).set(a,b[1])})});F(d.D(),function(a){b.Z(a,this.P(a))},this);return b};
W.prototype.subgraph=W.prototype.R;W.prototype.Va=function(){return H(G(Ea(this.s(),function(a){return a[1].d(a[0])}),function(a){return a[0]}))};W.prototype.nodes_with_selfloops=W.prototype.Va;W.prototype.oa=function(a){function b(a){return[a[0],a[0]]}a&&(b=function(a){var b=a[0];return[b,b,a[1].get(b)]});return H(G(Ea(this.s(),function(a){return a[1].d(a[0])}),b))};W.prototype.selfloop_edges=W.prototype.oa;W.prototype.Wa=function(){return this.oa().length};W.prototype.number_of_selfloops=W.prototype.Wa;
W.prototype.size=function(a){var b=V.F.apply(m,this.A(m,a).J())/2;return a!=m?b:Math.floor(b)};W.prototype.size=W.prototype.size;W.prototype.ca=function(a,b){return a==m?Math.floor(this.size()):this.C(a,b)?1:0};W.prototype.number_of_edges=W.prototype.ca;W.prototype.Ja=function(a,b){var c=eb(a),d=c[0],c=ab(ya(c,1),function(a){return[d,a]});this.e(c,b)};W.prototype.add_star=W.prototype.Ja;W.prototype.Ia=function(a,b){var c=eb(a),c=Ca(ya(c,0,c.length-1),ya(c,1));this.e(c,b)};W.prototype.add_path=W.prototype.Ia;
W.prototype.Ga=function(a,b){var c=eb(a),c=Ca(c,wa(ya(c,1),[c[0]]));this.e(c,b)};W.prototype.add_cycle=W.prototype.Ga;W.prototype.K=function(a){return a!=m?this.a(a)?hb([a]):hb(a):this.j.D()};W.prototype.nbunch_iter=W.prototype.K;function Sb(a){return function(b,c){b+=+c.c();return b+=+c.d(a)}}function Tb(a,b){return function(c,d){c=Fa(d.aa(),function(a,c){return a+ +O(c,b,1)},c);c+=+(d.d(a)&&O(d.get(a),b,1))}};function Y(a,b){if(!(this instanceof Y))return new Y(a,b);this.i={};this.j=X(this);this.q=X(this);this.z=X(this);this.l=this.q;a!=m&&yb(a,this);P(this.i,b||{});this.kb=this.q}y("jsnx.classes.DiGraph",Y);y("jsnx.DiGraph",Y);pa(Y,W);Y.__name__="DiGraph";p=Y.prototype;p.z=m;p.l=m;function Ub(a,b){return b!=m?a.z.get(b):a.z}function Vb(a,b){return b!=m?a.l.get(b):a.l}p.ea=function(a,b){this.j.d(a)?P(this.j.get(a),b):(this.l.set(a,X(this)),this.z.set(a,X(this)),this.j.set(a,b))};
p.S=function(a,b,c){c=c||{};this.O(a);this.O(b);var d=Vb(this,a),e={};d.d(b)?(e=d.get(b),P(e,c)):(P(e,c),Vb(this,a).set(b,e),Ub(this,b).set(a,e))};p.Ca=function(a,b){this.Qa(a)&&this.Qa(b)&&(Vb(this,a).remove(b),Ub(this,b).remove(a))};p.M=W.prototype.M;Y.prototype.remove_edges_from=Y.prototype.M;Y.prototype.Sa=function(a,b){return this.a(a)&&Vb(this,a).d(b)};Y.prototype.has_successor=Y.prototype.Sa;Y.prototype.Ra=function(a,b){return this.a(a)&&Ub(this,a).d(b)};Y.prototype.has_predecessor=Y.prototype.Ra;
Y.prototype.$a=W.prototype.W;Y.prototype.successors_iter=Y.prototype.$a;Y.prototype.Ya=function(a){this.a(a)||h(new T("The node "+a+" is not in the digraph."));return Ub(this,a).D()};Y.prototype.predecessors_iter=Y.prototype.Ya;Y.prototype.Za=W.prototype.V;Y.prototype.successors=Y.prototype.Za;Y.prototype.Xa=function(a){this.a(a)||h(new T("The node "+a+" is not in the digraph."));return Ub(this,a).fa()};Y.prototype.predecessors=Y.prototype.Xa;Y.prototype.V=W.prototype.V;Y.prototype.neighbors=Y.prototype.V;
Y.prototype.W=W.prototype.W;Y.prototype.neighbors_iter=Y.prototype.W;Y.prototype.f=W.prototype.f;Y.prototype.ma=W.prototype.f;Y.prototype.out_edges_iter=Y.prototype.ma;Y.prototype.ua=W.prototype.I;Y.prototype.out_edges=Y.prototype.ua;Y.prototype.s=function(a,b,c){var d=m,e=n,f=l;b!=m&&(e=b);c!=m&&(f=c);e?(d=Rb(this.z,a),f&&(d=bb(d,Rb(this.l,a)))):f&&(d=Rb(this.l,a));return d};Y.prototype.adjacency_iter=Y.prototype.s;Y.prototype.U=function(a,b){return this.T(a,b,l,n)};Y.prototype.in_edges_iter=Y.prototype.U;
Y.prototype.T=function(a,b,c,d){ha(a)&&(a=m);b=n;var e=l;c!=m&&(b=c);d!=m&&(e=d);b&&e&&h(Error("Why are you iterating over both directions?"));a=this.s(a,b,e);return gb(a,function(a){return Qb(a[1])},function(){})};Y.prototype.ia=function(a,b){return H(this.U(a,b))};Y.prototype.in_edges=Y.prototype.ia;Y.prototype.B=function(a,b){return this.qa(a,b,l,l)};Y.prototype.degree_iter=Y.prototype.B;Y.prototype.ha=function(a,b){return this.qa(a,b,l,n)};Y.prototype.in_degree_iter=Y.prototype.ha;
Y.prototype.qa=function(a,b,c,d){var e=n,f=l;c!=m&&(e=c);d!=m&&(f=d);node_nbrs=this.s(a,e,f);var g=Sb;b&&(g=Tb);return G(m,function(a){var c=0,d,s=g(a[0],b);e&&f?(d=a[0][0],c=s(0,a[0][1])+s(0,a[1][1])):(d=a[0],c=s(c,a[1]));return[d,c]})};Y.prototype.da=function(a,b){return this.qa(a,b,n,l)};Y.prototype.out_degree_iter=Y.prototype.da;Y.prototype.za=function(a,b){if(this.a(a))return this.ha(a,b).next()[1];var c=X(this);c.N(this.ha(a,b));return c};Y.prototype.in_degree=Y.prototype.za;
Y.prototype.Ba=function(a,b){if(this.a(a))return this.da(a,b).next()[1];var c=X(this);c.N(this.da(a,b));return c};Y.prototype.out_degree=Y.prototype.Ba;Y.prototype.clear=function(){this.l.clear();this.z.clear();this.j.clear();Ra(this.i)};Y.prototype.clear=Y.prototype.clear;Y.prototype.o=aa(n);Y.prototype.is_multigraph=Y.prototype.o;Y.prototype.h=aa(l);Y.prototype.is_directed=Y.prototype.h;
Y.prototype.Y=function(){var a=new Y(m,this.i);a.m(G(this.w(l),function(a){return[a[0],R(a[1])]}));a.e(G(this.f(j,l),function(a){return[a[0],a[1],R(a[2])]}));return a};Y.prototype.to_directed=Y.prototype.Y;Y.prototype.pa=function(a){var b=new W;b.name(this.name());b.m(G(this.w(l),function(a){return[a[0],R(a[1])]}));a=a?Ea(this.f(l),function(a){return this.C(a[1],a[0])},this):this.f(l);b.e(G(a,function(a){return[a[0],a[1],R(a[2])]}));b.i=R(this.i);return b};Y.prototype.to_undirected=Y.prototype.pa;
Y.prototype.reverse=function(a){(a=!t(a)||a)?(a=new this.constructor(m,{name:"Reverse of ("+this.name()+")"}),a.m(G(this.w(l),function(a){return[a[0],R(a[1])]})),a.e(G(this.f(l),function(a){return[a[1],a[0],R(a[2])]})),a.i=R(this.i)):(a=this.l,this.l=this.z,this.z=a,this.q=this.l,a=this);return a};Y.prototype.reverse=Y.prototype.reverse;
Y.prototype.R=function(a){a=this.K(a);var b=new this.constructor(this.ra),c=b.l,d=b.z,e=this.l;F(a,function(a){var g=a[0],k=X(b);c.set(g,k);F(Qb(e.get(g)),function(a){var b=a[0];c.d(b)&&(k.set(b,a[1]),d.get(b).set(g,a[1]))})});F(H_adj.D(),function(a){b.Z(a,this.P(a))},this);return b};Y.prototype.subgraph=Y.prototype.R;function Z(a,b){if(!(this instanceof Z))return new Z(a,b);W.call(this,a,b)}pa(Z,W);y("jsnx.classes.MultiGraph",Z);y("jsnx.MultiGraph",Z);Z.__name__="MultiGraph";Z.prototype.v=function(a,b,c,d){c!=m&&(!x(c)&&!ja(c))&&(d=c,c=m);d=d||{};"object"!==r(d)&&h(new T("The attr_dict argument must be an object."));this.S(a,b,c,d)};Z.prototype.add_edge=Z.prototype.v;
Z.prototype.S=function(a,b,c,d){this.O(a);this.O(b);var e=this.g(a),f=this.g(b);if(e.d(b)){keydict=e.get(b);if(c==m)for(c=keydict.c();keydict.d(c);)c+=1;datadict=keydict.get(c,{});P(datadict,d);keydict.set(c,datadict)}else c!=m||(c=0),datadict={},P(datadict,d),keydict=new Ob,keydict.set(c,datadict),e.set(b,keydict),f.set(a,keydict)};
Z.prototype.e=function(a,b){b=b||{};"object"!==r(b)&&h(new T("The attr_dict argument must be an object."));Q(a,function(a){var d=Za(a),e,f,g=m,k={};4===d?(e=a[0],f=a[1],g=a[2],k=a[3]):3===d?(e=a[0],f=a[1],k=a[2]):2===d?(e=a[0],f=a[1]):h(new T("Edge tuple "+Hb(a)+" must be a 2-tuple, 3-tuple or 4-tuple."));a=Wa(b);P(a,k);this.S(e,f,g,a)},this)};Z.prototype.add_edges_from=Z.prototype.e;
Z.prototype.X=function(a,b,c){var d=this.g(a);(!t(d)||!d.d(b))&&h(new T("The edge "+a+"-"+b+" is not in the graph"));this.na(a,b,c)};Z.prototype.remove_edge=Z.prototype.X;Z.prototype.na=function(a,b,c){var d=this.g(a),e=d.get(b);c!=m?(e.d(c)||h(new T("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),e.remove(c)):e.remove(e.D().next());0===e.c()&&(d.remove(b),a!=b&&this.g(b).remove(a))};
Z.prototype.M=function(a){Q(a,function(a){try{this.na(a[0],a[1],a[2])}catch(c){c instanceof T||h(c)}},this)};Z.prototype.remove_edges_from=Z.prototype.M;Z.prototype.C=function(a,b,c){var d=m;if(c!=m)return d=this.g(a),t(d)?d.d(b)&&d.get(b).d(c):n;d=this.g(a);return t(d)&&d.d(b)};Z.prototype.has_edge=Z.prototype.C;Z.prototype.I=function(a,b,c){return H(this.f(a,b,c))};Z.prototype.edges=Z.prototype.I;
Z.prototype.ga=function(a,b,c,d){t(d)||(d=m);return this.a(a)&&this.g(a).d(b)?c!=m?this.g(a).get(b).get(c,d):this.g(a).get(b):d};Z.prototype.get_edge_data=Z.prototype.ga;Z.prototype.B=function(a,b){var c,d;c=this.s(a);b!=m?Wb:d=Xb;return G(c,function(a){var c=a[0],g=0,g=d(c,b)(0,a[1]);return[c,g]})};Z.prototype.degree_iter=Z.prototype.B;Z.prototype.o=aa(l);Z.prototype.is_multigraph=Z.prototype.o;Z.prototype.h=aa(n);Z.prototype.is_directed=Z.prototype.h;
Z.prototype.Y=function(){var a=new $(m,this.i);a.m(this.w(l));a.e(G(this.f(m,l,l),function(a){return[a[0],a[1],a[2],R(a[3])]}));return a};Z.prototype.to_directed=Z.prototype.Y;Z.prototype.oa=function(a,b){function c(){}var d=[],c=a?b?function(a,b){d.push([a,a,b[0],b[1]])}:function(a,b){d.push([a,a,b[1]])}:b?function(a,b){d.push([a,a,b[0]])}:function(a){d.push([a,a])};F(this.s(),function(a){var b=a[1],d=a[0];b.d(d)&&F(Qb(b.get(d)),function(a){c(d,a)})});return d};Z.prototype.selfloop_edges=Z.prototype.oa;
Z.prototype.ca=function(a,b){return a==m?this.size():this.a(a)&&this.C(a,b)?this.g(a).get(b).c():0};Z.prototype.number_of_edges=Z.prototype.ca;Z.prototype.R=function(a){a=this.K(a);var b=new this.constructor(m,this.i),c=b.q,d=this.q,e=b.j;F(a,function(a){var b=X(this);c.set(a,b);F(Qb(d.get(a)),function(d){var e=d[1];d=d[0];if(c.d(d)){var C=X(this);C.N(G(Qb(e),function(a){return[a[0],R(a[1])]}));b.set(d,C);c.get(d).set(a,C)}})});F(c.D(),function(a){e.set(a[0],a[1])});return b};
Z.prototype.subgraph=Z.prototype.R;function Xb(a){return function(b,c){var d=0,d=Fa(c.aa(),function(a){d+=a.c()},d);return d+(+c.d(a)&&c.get(a).c())}}function Wb(a,b){return function(c,d){var e;e=Fa(d.aa(),function(a,c){return a+Fa(c.aa(),function(a,c){return a+O(c,b,1)},0)},0);d.d(a)&&(e=Fa(d.get(a).aa(),function(a,c){return a+O(c,b,1)},e));return e}};function $(a,b){if(!(this instanceof $))return new $(a,b);Y.call(this,a,b)}pa($,Y);var Yb=$.prototype,Zb=Z.prototype,$b;for($b in Zb)Zb.hasOwnProperty($b)&&"constructor"!==$b&&(Yb[$b]=Zb[$b]);y("jsnx.classes.MultiDiGraph",$);y("jsnx.MultiDiGraph",$);$.__name__="MultiDiGraph";$.prototype.ea=function(a,b){this.a(v)||(this.l.set(v,X(this)),this.z.set(v,X(this)),this.j.set(v,b||{}))};
$.prototype.v=function(a,b,c,d){c!=m&&(!x(c)&&!ja(c))&&(d=c,c=m);d=d||{};"object"!==r(d)&&h(new T("The attr_dict argument must be an object."));this.Ha(a,b,c,d)};$.prototype.add_edge=$.prototype.v;
$.prototype.S=function(a,b,c,d){this.O(a);this.O(b);if(this.C(a,b)){keydict=this.g(a).get(b);if(c==m)for(c=keydict.c();keydict.d(c);)c+=1;datadict=keydict.get(c,{});P(datadict,d);keydict.set(c,datadict)}else c!=m||(c=0),datadict={},P(datadict,d),keydict=new Ob,keydict.set(c,datadict),Vb(this,a).set(b,keydict),Ub(this,b).set(a,keydict)};$.prototype.X=function(a,b,c){(!this.a(a)||!this.C(a,b))&&h(new T("The edge "+a+"-"+b+" is not in the graph"));this.Ca(a,b,c)};$.prototype.remove_edge=$.prototype.X;
$.prototype.Ca=function(a,b,c){var d=Vb(this,a).get(b);c!=m?(d.d(c)||h(new T("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),d.remove(c)):d.remove(d.D().next());0===d.c()&&(Vb(this,a).remove(b),Ub(this,b).remove(a))};
$.prototype.T=function(a,b,c,d,e){ha(a)&&(b=a,a=m);var f=n,g=l;d!=m&&(f=d);e!=m&&(g=e);f&&g&&h(Error("Why are you iterating over both directions?"));var k;k=b?c?g?function(a,b,c){return[a,b,c[0],c[1]]}:function(a,b,c){return[b,a,c[0],c[1]]}:g?function(a,b,c){return[a,b,c[1]]}:function(a,b,c){return[b,a,c[1]]}:c?g?function(a,b,c){return[a,b,c[0]]}:function(a,b,c){return[b,a,c[0]]}:g?function(a,b){return[a,b]}:function(a,b){return[b,a]};var q=m,C=m;a=this.s(a,f,g);return gb(a,function(a){q=a[0];return Qb(a[1])},
function(a){C=a[0];return Qb(a[1])},function(a){return k(q,C,a)})};$.prototype.f=function(a,b,c){return this.T(a,b,c,n,l)};$.prototype.edges_iter=$.prototype.f;$.prototype.ma=$.prototype.f;$.prototype.ua=function(a,b,c){return H(this.ma(a,b,c))};$.prototype.out_edges=$.prototype.ua;$.prototype.U=function(a,b,c){return this.T(a,b,c,l,n)};$.prototype.in_edges_iter=$.prototype.U;$.prototype.ma=function(a,b,c){return this.T(a,b,c,n,l)};$.prototype.out_edges_iter=$.prototype.ma;
$.prototype.ia=function(a,b,c){return H(this.U(a,b,c))};$.prototype.in_edges=$.prototype.ia;$.prototype.qa=function(a,b,c,d){var e=n,f=l;c!=m&&(e=c);d!=m&&(f=d);node_nbrs=this.s(a,e,f);var g=Xb;b&&(g=Wb);return G(m,function(a){var c=0,d,s=g(a[0],b);e&&f?(d=a[0][0],c=s(0,a[0][1])+s(0,a[1][1])):(d=a[0],c=s(c,a[1]));return[d,c]})};$.prototype.B=Y.prototype.B;$.prototype.degree_iter=$.prototype.B;$.prototype.ha=Y.prototype.mb;$.prototype.in_degree_iter=$.prototype.ha;$.prototype.da=Y.prototype.da;
$.prototype.out_degree_iter=$.prototype.da;$.prototype.o=aa(l);$.prototype.is_multigraph=$.prototype.o;$.prototype.h=aa(l);$.prototype.is_directed=$.prototype.h;$.prototype.Y=function(){return qb(this)};$.prototype.to_directed=$.prototype.Y;$.prototype.pa=function(a){var b=new Z;b.i=R(this.i);b.m(this.w(l));var c=this;a?F(this.f(m,l,l),function(a){c.C(a[0],a[1],a[2])&&N.Ha(a[0],a[1],a[2],R(a[3]))}):b.e(G(this.f(m,l,l),function(a){return[a[0],a[1],a[2],R(a[3])]}));return b};
$.prototype.to_undirected=$.prototype.pa;$.prototype.R=function(a){a=this.K(a);var b=this,c=new this.constructor(m,this.i),d=c.l,e=c.z,f=this.l;Q(a,function(a){var b=X(c);d.set(a,b);F(Qb(f.get(a)),function(c){var f=c[0];c=c[1];d.d(f)&&(c=c.$(),b.set(f,c),e.get(f).set(a,c))})});F(a,function(a){c.O(a,b.P(a))});return c};$.prototype.subgraph=$.prototype.R;
$.prototype.reverse=function(a){(a=!t(a)||a)?(a=new this.constructor(m,this.i),a.name("Reverse of ("+this.name()+")"),a.m(this.w(l)),a.e(G(this.f(l,l),function(a){return[a[1],a[0],a[2],R(a[3])]}))):(a=this.l,this.l=this.z,this.z=a,this.q=this.l,a=this);return a};$.prototype.reverse=$.prototype.reverse;y("jsnx.nodes",function(a){return a.nodes()});y("jsnx.nodes_iter",function(a){return a.w()});y("jsnx.edges",function(a,b){return a.I(b)});y("jsnx.edges_iter",function(a,b){return a.f(b)});y("jsnx.degree",function(a,b,c){return a.A(b,c)});y("jsnx.neighbors",function(a,b){return a.V(b)});y("jsnx.number_of_nodes",function(a){return a.la()});y("jsnx.number_of_edges",function(a){return a.ca()});y("jsnx.density",function(a){var b=a.la(),c=a.ca();return 0===c?0:a.h()?c/(b*(b-1)):2*c/(b*(b-1))});
y("jsnx.degree_histogram",function(a){a=L(a.A());for(var b=Math.max.apply(Math,a)+1,c=[],d=0;d<b;d++)c[d]=0;ra(a,function(a){c[a]+=1});return c});y("jsnx.is_directed",function(a){return a.h()});y("jsnx.freeze",function(a){function b(){h(new T("Frozen graph can't be modified"))}a.Z=b;a.m=b;a.sa=b;a.va=b;a.v=b;a.e=b;a.X=b;a.M=b;a.clear=b;a.Oa=l;return a});y("jsnx.is_frozen",function(a){return!!a.Oa});y("jsnx.subgraph",function(a,b){return a.R(b)});
y("jsnx.create_empty_copy",function(a,b){t(b)||(b=l);var c=new a.constructor;b&&c.m(a);return c});
y("jsnx.info",function(a,b){var c="";if(b!=m)a.a(b)||h(new T("node "+b+" not in graph")),c=c+("Node "+b+" has the following properties:\n")+("Degree: "+a.A(b)+"\n"),c+="Neighbors: "+a.V(b).join(" ");else{var c=c+("Name: "+a.name()+"\n"),c=c+("Type: "+a.constructor.__name__+"\n"),c=c+("Number of nodes: "+a.la()+"\n"),c=c+("Number of edges: "+a.ca()+"\n"),d=a.la();if(0<d)if(a.h())c+="Average in degree: "+(V.F.apply(m,L(a.za()))/d).toFixed(4)+"\n",c+="Average out degree: "+(V.F.apply(m,L(a.Ba()))/d).toFixed(4);
else var e=V.F.apply(m,L(a.A())),c=c+("Average degree: "+(e/d).toFixed(4))}return c});y("jsnx.set_node_attributes",function(a,b,c){I(c,function(c,e){a.P[e][b]=c})});function ac(a,b){var c={};I(a.P,function(a,e){b in a&&(c[e]=a[b])});return c}y("jsnx.get_node_attributes",ac);y("jsnx.set_edge_attributes",function(a,b,c){I(c,function(b,c){c=c.split(",");a.t(c[0])[c[1]]=b})});ac=function(a,b){var c={};I(a.I(l),function(a){b in a[2]&&(c[[a[0],a[1]]]=a[2][b])});return c};y("jsnx.get_edge_attributes",{}.lb);var bc={};function cc(a,b){a.h()&&h(new T("triangles() is not defined for directed graphs."));if(a.a(b))return Math.floor(dc(a,b).next()[2]/2);var c={};F(dc(a,b),function(a){c[a[0]]=Math.floor(a[2]/2)});return c}y("jsnx.triangles",cc);
function dc(a,b){a.o()&&h(new T("Not defined for multigraphs."));var c;c=b!=m?gb(a.K(b),function(b){return[b,a.t(b)]}):pb(a.adj);return G(c,function(b){var c=new S(M(b[1])),f=0;c.remove(b[0]);F(c,function(b){var d=new S(M(a.t(b)));d.remove(b);f+=vb(c,d).c()});return[b[0],c.c(),f]})}
y("jsnx.average_clustering",function(a,b,c,d){2===arguments.length?x(b)?(c=b,b=m):ha(b)&&(d=b,b=m):3===arguments.length&&ha(c)&&(d=c,c=m);c!=m||(c=m);d!=m||(d=l);var e=L(ec(a,b,c));d||(e=sa(e,function(a){return 0<a}));return V.F.apply(V,e)/e.length});
function ec(a,b,c){a.h()&&h(new T("Clustering algorithms are not defined for directed graphs."));if(c!=m){var d=c;a.o()&&h(new T("Not defined for multigraphs."));t(d)||(d="weight");var e;if(0===a.I().length)c=1;else{c=a.I(l);var f=function(a){return O(a[2],d,1)};c=ka(f)?ab(c,function(){return f.apply(m,arguments)}):eb(c);c=Math.max.apply(m,c)}e=c;c=b!=m?gb(a.K(b),function(b){return[b,a.t(b)]}):pb(a.adj);c=G(c,function(b){var c=b[0],f=new S(M(b[1]));f.remove(c);var g=0,D=new S;F(f,function(b){var k=
O(a.t(c)[b],d,1)/e;D.add(b);var ga=wb(new S(M(a.t(b))),D);F(vb(f,ga),function(f){var C=O(a.t(b)[f],d,1)/e;f=O(a.t(c)[f],d,1)/e;g+=Math.pow(k*C*f,1/3)})});return[c,f.c(),2*g]})}else c=dc(a,b);var g={};F(c,function(a){g[a[0]]=0===a[2]?0:a[2]/(a[1]*(a[1]-1))});return a.a(b)?L(g)[0]:g}y("jsnx.clustering",ec);y("jsnx.transitivity",function(a){var b=0,c=0;F(dc(a),function(a){c+=a[1]*(a[1]-1);b+=a[2]});return 0===b?0:b/c});
y("jsnx.square_clustering",function(a,b){var c=b==m?a:a.K(b),d={};F(c,function(b){var c=d[b]=0;F(db(M(a.t(b))),function(g){var k=g[0];g=g[1];var q=vb(new S(M(a.t(k))),M(a.t(g)));q.remove(b);q=q.c();d[b]+=q;var C=q+1,s=a.t(k);g in s&&(C+=1);c+=(Qa(a.t(k))-C)*(Qa(a.t(g))-C)+q});0<c&&(d[b]/=c)});return a.a(b)?L(d)[0]:d});function fc(a){var b=-1,c={},d=new S;F(a.s(),function(a){var e=new S(M(a[1]));e.remove(a[0]);var f=e.c();f>b?(c[a[0]]=d=e,b=f):c[a[0]]=e});var e=new S(M(c)),f=wb(e,d),g=new S,k=[],q=[];a=new B;a.next=function(){0===f.c()&&0===k.length&&h(A);var a,s;if(0<f.c())a=La(f),f.remove(a);else{var D=k.pop();e=D[0];g=D[1];f=D[2];q.pop();return this.next()}q.push(a);e.remove(a);g.add(a);var U=c[a],D=vb(e,U),U=vb(g,U);if(0===D.c()&&(0===U.c()&&(s=xa(q)),q.pop(),s))return s;if(0===U.c()&&1===D.c())return s=wa(q,
D.J()),q.pop(),s;var Da=D.c(),ga=-1,Ga,ia;for(s=E(U);(a=La(s,m))!==m&&!(a=vb(D,c[a]),ia=a.c(),ia>ga&&(Ga=a,ga=ia,ga===Da)););if(ga===Da)return q.pop(),this.next();b=-1;for(s=E(D);(a=La(s,m))!==m&&!(a=vb(D,c[a]),ia=a.c(),ia>b&&(d=a,b=ia,b===Da-1)););ga>b&&(d=Ga);k.push([e,g,f]);e=D;g=U;f=wb(e,d);return this.next()};return a}y("jsnx.find_cliques",fc);
y("jsnx.find_cliques_recursive",function(a){var b={};F(a.s(),function(a){var c=new S(M(a[1]));c.remove(a[0]);b[a[0]]=c});a:{for(var c in b){a=n;break a}a=l}if(a)return[];a=new S(M(b));c=new S;var d=[];gc(b,a,c,[],d);return d});
function gc(a,b,c,d,e){var f=-1,g=b.c(),k,q,C,s;for(q=E(c);(C=La(q,m))!==m;)if(C=vb(b,a[C]),s=C.c(),s>f&&(k=C,f=s,s===g))return;F(b,function(c){c=vb(b,a[c]);var d=c.c();d>f&&(k=c,f=d)});g=wb(b,k);F(g,function(f){b.remove(f);d.push(f);var g=a[f];f=vb(b,g);g=vb(c,g);f.ba()&&g.ba()?e.push(xa(d)):g.ba()&&1===f.c()?e.push(wa(d,f.J())):gc(a,f,g,d,e);c.add(d.pop())})}y("jsnx.graph_clique_number",function(a,b){b!=m||(b=fc(a));var c=0;Q(b,function(a){c=a.length>c?a.length:c});return c});
y("jsnx.graph_number_of_cliques",function(a,b){b!=m||(b=fc(a));return eb(b).length});function hc(a,b,c){c!=m||(c=H(fc(a)));b!=m||(b=a.nodes());var d;if(fa(b))d={},ra(b,function(a){d[a]=sa(c,function(b){return 0<=qa(b,a)||0<=qa(b,a+"")}).length});else{var e=b;d=sa(c,function(a){return 0<=qa(a,e)||0<=qa(a,e+"")}).length}return d}y("jsnx.number_of_cliques",hc);function ic(a,b){if(a.Q()!=b.Q())return n;var c=a.A(),d=cc(a),e=hc(a),f=[],g;for(g in c)f.push([c[g],d[g],e[g]]);f.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});var c=b.A(),d=cc(b),e=hc(b),k=[];for(g in c)k.push([c[g],d[g],e[g]]);k.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});return!za(f,k,function(a,b){return za(a,b)})?n:l}y("jsnx.algorithms.isomorphism.could_be_isomorphic",ic);y("jsnx.could_be_isomorphic",ic);
function jc(a,b){if(a.Q()!=b.Q())return n;var c=a.A(),d=cc(a),e=[],f;for(f in c)e.push([c[f],d[f]]);e.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});var c=b.A(),d=cc(b),g=[];for(f in c)g.push([c[f],d[f]]);g.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});return!za(e,g,function(a,b){return za(a,b)})?n:l}y("jsnx.algorithms.isomorphism.fast_could_be_isomorphic",jc);y("jsnx.fast_could_be_isomorphic",jc);
function kc(a,b){if(a.Q()!=b.Q())return n;var c=L(a.A());c.sort();var d=L(b.A());d.sort();return!za(c,d)?n:l}y("jsnx.algorithms.isomorphism.faster_could_be_isomorphic",kc);y("jsnx.faster_could_be_isomorphic",kc);function lc(a,b){if("eg"===b)return mc(a);if(b==m||"hh"===b)return nc(a);h(new Ab("`opt_method` must be 'eg' or 'hh'"))}y("jsnx.is_valid_degree_sequence",lc);function nc(a){if(0===a.length)return l;if(!Oa(a)||0>Math.min.apply(m,a)||0!==V.F.apply(m,a)%2)return n;for(a=xa(a);0<a.length;){z.sort.call(a,Ba);if(0>a[0])break;var b=a.pop();if(0===b)return l;if(b>a.length)break;for(var c=a.length-1,b=a.length-(b+1);c>b;c--)a[c]-=1}return n}y("jsnx.is_valid_degree_sequence_havel_hakimi",nc);
function mc(a){if(0===a.length)return l;if(!Oa(a)||0>Math.min.apply(m,a)||0!==V.F.apply(m,a)%2)return n;var b=a.length,c=xa(a).sort(function(a,b){return b-a}),d=[],e;e=1;for(a=c.length;e<a;e++)c[e]<c[e-1]&&d.push(e);var f,g;e=0;for(a=d.length;e<a;e++)if(f=V.F.apply(m,c.slice(0,d[e])),g=d[e]*(d[e]-1)+V.F.apply(m,H(G(cb(d[e],b),function(a){return Math.min(d[e],c[a])}))),f>g)return n;return l}y("jsnx.is_valid_degree_sequence_erdos_gallai",mc);var oc,pc=m,xc="add_node add_nodes_from add_edge add_edges_from remove_node remove_nodes_from remove_edge remove_edges_from clear".split(" ");
y("jsnx.draw",function(a,b,c){function d(){J.attr("transform",function(a){return["translate(",a.x,",",a.y,")scale(",ea,")"].join("")});Gb()}ha(b)&&(c=b,b=m);b=b||pc||{};var e=b.d3||window.d3,f={};ib(f,yc,b);pc=b;e||h(Error("D3 requried for draw()"));f.element==m&&oc==m&&h(Error("Output element required for draw()"));oc=O(f,"element",oc);e.select(oc).select("svg.jsnx").remove();var g=e.select(oc),k=g.append("svg").classed("jsnx",l).attr("pointer-events","all"),q=k.append("g");b=q.append("g").classed("edges",
l).selectAll("g.edge");var C=q.append("g").classed("nodes",l).selectAll("g.node"),s=e.layout.force(),D=f.width||parseInt(g.style("width"),10),U=f.height||parseInt(g.style("height"),10),Da=f.layout_attr,g=f.nodelist||m,ga,Ga,ia,qc=a.h(),Sa=f.weighted,J=C,K=b;if(f.with_labels){var ua=f.labels;ga="object"===r(ua)?function(a){return O(ua,a.node,"")}:ka(ua)?ua:x(ua)?function(a){return a.data[ua]}:function(a){return a.node}}f.labels=ga;if(Sa){var Ha=f.weights;ia="object"===r(Ha)?function(a){return O(Ha,
a.node,1)}:ka(Ha)?Ha:x(Ha)?function(a){return O(a.data,Ha,1)}:aa(1)}if(f.with_edge_labels){var Ia=f.edge_labels;Ga=Sa&&!t(Ia)?ia:"object"===r(Ia)?function(a){return O(ua,a.node,"")}:ka(Ia)?Ia:x(Ia)?function(a){return a.data[Ia]}:function(a){return a.edge};f.edge_labels=Ga}if(Sa&&f.weighted_stroke){var Sa=Fa(a.f(l),function(a,b){b=ia({data:b[2]});return a>b?a:b},0),Oc=e.scale.linear().range([1,f.edge_style["stroke-width"]]).domain([0,Sa]);f.edge_style["stroke-width"]=function(a){return Oc(ia.call(this,
a))}}k.select("svg.jsnx").remove();k.attr("width",D+"px").attr("height",U+"px").style("opacity",1E-6).transition().duration(1E3).style("opacity",1);var Pc={size:l,nodes:l,links:l,start:l};Q(Da,function(a){if(!(a in Pc))s[a](Da[a])});s.nodes([]).links([]).size([D,U]);var Ta=1,ea=1;if(f.pan_zoom.enabled){var rc=f.pan_zoom.scale,Ja=f.edge_style["stroke-width"];ka(Ja)?f.edge_style["stroke-width"]=function(){var a=Ja.apply(this,arguments);return ea*(+a||parseInt(a,10))}:(Ja=+Ja||parseInt(Ja,10),f.edge_style["stroke-width"]=
function(){return ea*Ja});var jb=n,sc=1,tc=Ta;k.call(e.behavior.zoom().on("zoom",function(){var a=e.event.sourceEvent.shiftKey;(a=rc&&a||!(rc||a))&&!jb?(sc=e.event.scale,tc=Ta,jb=l):!a&&jb&&(jb=n);Ta=a?tc*(e.event.scale/sc):Ta;ea=!a?Ta/e.event.scale:ea;a=e.event.translate;q.attr("transform","translate("+a[0]+","+a[1]+")scale("+e.event.scale+")");q.selectAll("g.edge > .line").style("stroke-width",f.edge_style["stroke-width"]);d()}))}var Gb=da;if(qc){k.append("defs").append("marker").attr("id","Triangle").attr("markerUnits",
"strokeWidth").attr("refX","7").attr("refY","5").attr("viewBox","0 0 10 10").attr("orient","auto").append("path").attr("d","M 0 0 L 10 5 L 0 10 z");f.edge_attr["marker-end"]="url(#Triangle)";f.edge_style.fill="none";var kb=f.layout_attr.linkDistance,Ua=f.edge_offset;ka(kb)||(kb=function(){return f.layout_attr.linkDistance});fa(Ua)&&(Ua=function(){return f.edge_offset});ja(Ua)&&(Ua=function(){return[f.edge_offset,f.edge_offset]});Gb=function(){K.each(function(a){if(a.source!==a.target){var b=e.select(this),
c=a.source.x,d=a.source.y,f=a.target.x,g=a.target.y,k=V.xa(c,d,f,g),f=Math.sqrt(Math.pow(f-c,2)+Math.pow(g-d,2)),g=Ua(a),g=[g[0]*ea,g[1]*ea];b.attr("transform",["translate(",c,",",d,")rotate(",k,")"].join(""));if(c=a.G.C(a.target.node,a.source.node)){var d=kb(a)/3,k=-d/(f/2),q=k*f;b.select(".line").attr("d",["M",g[0],k*g[0],"Q",f/2,-d,f-g[1],-k*(f-g[1])+q].join(" "))}else b.select(".line").attr("d",["M",g[0],"0 L",f-g[1],0].join(" "));g=1/ea;b.select("text").attr("x",f*g/2).attr("y",c?g*(-kb(a)/4):
0).attr("transform","scale("+ea+")")}})}}else Gb=function(){K.each(function(a){if(a.source!==a.target){var b=e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,k=a.target.y;a=V.xa(c,d,g,k);g=Math.sqrt(Math.pow(g-c,2)+Math.pow(k-d,2));k=g/2;b.attr("transform",["translate(",c,",",d,")rotate(",a,")"].join(""));b.select(".line").attr("d",["M 0 0 L",g,"0"].join(" "));f.with_edge_labels&&b.select("text").attr("x",k*(1/ea)).attr("y",0).attr("transform","scale("+ea+")"+(90<a&&279>a?"rotate(180,"+k*(1/
ea)+",0)":""))}})};s.on("tick",d);k=a.w();D=a.f();g&&(c=n,k=a.K(g),D=a.f(g));J=zc(a,k,s,C,f.node_shape,ga);K=Ac(a,D,s,b,Ga);Bc(J,{attr:f.node_attr,style:f.node_style,ka:f.label_style,ja:f.label_attr},f.with_labels);Cc(K,{attr:f.edge_attr,style:f.edge_style,ka:f.edge_label_style,ja:f.edge_label_attr},f.with_edge_labels,m,qc);if(c){Dc(a,n);var na=a.constructor.prototype,lb=f.node_shape,mb={attr:f.node_attr,style:f.node_style,ja:f.label_attr,ka:f.label_style},uc={attr:f.edge_attr,style:f.edge_style,
ja:f.edge_label_attr,ka:f.edge_label_style},nb=f.labels,vc=f.edge_labels,ob=f.with_labels,wc=f.with_edge_labels,Qc=a.h();a.add_node=a.Z=function(a){var b=!this.a(a);na.add_node.apply(this,arguments);b&&(J=zc(this,[a],s,J,lb,nb));Bc(J,mb,ob,[a]);s.start()};a.add_nodes_from=a.m=function(a){var b=sa(eb(a),function(a){return!this.a(w(a)?a[0]:a)},this);na.add_nodes_from.apply(this,arguments);0<b.length&&(J=zc(this,b,s,J,lb,nb));Bc(J,mb,ob,a);s.start()};a.add_edge=a.v=function(b,c){var d=!this.C(b,c),e=
[];d&&(e=sa(b==c?[b]:[b,c],function(a){return!this.a(a)},this));na.add_edge.apply(a,arguments);0<e.length&&(J=zc(this,e,s,J,lb,nb),Bc(J,mb,ob,e));d&&(K=Ac(this,[[b,c]],s,K,vc));Cc(K,uc,wc,[[b,c]],Qc);s.start()};a.add_edges_from=a.e=function(b){var c=[],d=[],e={},f={},g=this.h();Q(b,function(a){var b=a[0];a=a[1];if(!this.C(b,a)&&!([b,a]in e)&&(g||!([a,b]in e)))c.push([b,a]),e[[b,a]]=l,!this.a(b)&&!(b in f)&&(d.push(b),f[b]=l),!this.a(a)&&!(a in f)&&(d.push(a),f[a]=l)},this);na.add_edges_from.apply(a,
arguments);0<d.length&&(J=zc(this,d,s,J,lb,nb),Bc(J,mb,ob,d));0<c.length&&(K=Ac(this,c,s,K,vc));Cc(K,uc,wc,c,g);s.start()};a.remove_node=a.sa=function(b){try{if(this.a(b)){J=Ec(this,[b],s,J);var c=this.f([b]);this.h()&&(c=Ka(c,this.U([b])));K=Fc(this,c,s,K);s.resume()}}catch(d){}na.remove_node.apply(a,arguments)};a.remove_nodes_from=a.va=function(b){try{J=Ec(this,b,s,J);var c=this.f(b);this.h()&&(c=Ka(c,this.U(b)));K=Fc(this,c,s,K);s.resume()}catch(d){}na.remove_nodes_from.apply(a,arguments)};a.remove_edge=
a.X=function(b,c){try{K=Fc(this,[[b,c]],s,K),s.resume()}catch(d){}na.remove_edge.apply(a,arguments)};a.remove_edges_from=a.M=function(b){try{K=Fc(this,b,s,K),s.resume()}catch(c){}na.remove_edges_from.apply(a,arguments)};a.clear=a.clear=function(){J=J.data([],Gc);J.exit().remove();K=K.data([],Hc);K.exit().remove();s.nodes([]).links([]).resume();na.clear.apply(a,arguments)};a.bound=l}else a.bound?Dc(a):Ic(a);s.start();return s});
function zc(a,b,c,d,e,f){var g=c.nodes();Q(b,function(b){var c=a.node[b];b={node:b,data:c,G:a};g.push(b);c.__d3datum__=b});d=d.data(g,Gc);b=d.enter().append("g").classed("node",l).call(c.drag);b.append(e).classed("node-shape",l);f&&b.append("text").text(f);return d}
function Ac(a,b,c,d,e){var f=c.links();Q(b,function(b){var c=b[0],d=b[1];b=b[2]||a.ga(c,d);c={edge:[c,d],redge:[d,c],source:a.node[c].__d3datum__,target:a.node[d].__d3datum__,data:b,G:a};f.push(c);b.__d3datum__=c});d=d.data(f,Hc);b=d.enter().append("g").classed("edge",l);b.append("path").classed("line",l);e&&b.append("text").text(e);return d}
function Bc(a,b,c,d){if(d!=m){var e={};Q(d,function(a){e[w(a)?a[0]:a]=l});a=a.filter(function(a){return a.node in e})}var f=a.selectAll(".node-shape");I(b.attr,function(a,b){f.attr(b,a)});I(b.style,function(a,b){f.style(b,a)});if(c){var g=a.selectAll("text");I(b.ja,function(a,b){g.attr(b,a)});I(b.ka,function(a,b){g.style(b,a)})}}
function Cc(a,b,c,d,e){if(d!=m){var f={};Q(d,function(a){f[[a[0],a[1]]]=l});a=a.filter(function(a){return a.edge in f||e||a.redge in f})}var g=a.selectAll(".line");I(b.attr,function(a,b){g.attr(b,a)});I(b.style,function(a,b){g.style(b,a)});if(c){var k=a.selectAll("text");I(b.ja,function(a,b){k.attr(b,a)});I(b.ka,function(a,b){k.style(b,a)})}}function Gc(a){return a.node}function Hc(a){return a.edge}
function Ec(a,b,c,d){var e=c.nodes();Q(a.K(b),function(b){va(e,a.node[b].__d3datum__)});d=d.data(e,Gc);d.exit().remove();return d}function Fc(a,b,c,d){var e=c.links();Q(b,function(b){va(e,O(a.ga(b[0],b[1],{}),"__d3datum__",m))});d=d.data(e,Hc);d.exit().remove();return d}y("jsnx.is_bound",function(a){return a.bound});function Dc(a,b){if(a.bound){var c=a.constructor.prototype;ra(xc,function(b){a[b]=c[b]});delete a.bound;(!t(b)||b)&&Ic(a)}}y("jsnx.unbind",Dc);
function Ic(a){Q(a.w(l),function(a){Va(a[1])});Q(a.f(l),function(a){Va(a[2])})}
var yc={layout_attr:{charge:-120,linkDistance:40},node_shape:"circle",node_attr:{r:10},node_style:{stroke:"#333",fill:"#999",cursor:"pointer"},edge_attr:{},edge_style:{stroke:"#000","stroke-width":2},label_attr:{},label_style:{"text-anchor":"middle","dominant-baseline":"central",cursor:"pointer","-webkit-user-select":"none",fill:"#000"},edge_label_attr:{},edge_label_style:{"font-size":"0.8em","dominant-baseline":"central","text-anchor":"middle","-webkit-user-select":"none"},with_labels:n,with_edge_labels:n,
edge_offset:10,weighted:n,weights:"weight",weighted_stroke:l,pan_zoom:{enabled:l,scale:l}};function Jc(a,b){var c=Kc(a,b);c.name("complete_graph("+a+")");1<a&&c.e(c.h()?fb(cb(a)):db(cb(a)));return c}y("jsnx.complete_graph",Jc);y("jsnx.cycle_graph",function(a,b){var c=Lc(a,b);c.name("cycle_graph("+a+")");1<a&&c.v(a-1,0);return c});function Kc(a,b){a instanceof W&&(b=a,a=m);a!=m||(a=0);var c;b!=m?(c=b,c.clear()):c=new W;c.m(cb(a));c.name("empty_graph("+a+")");return c}y("jsnx.empty_graph",Kc);y("jsnx.null_graph",function(a){a=Kc(0,a);a.name("null_graph()");return a});
function Lc(a,b){var c=Kc(a,b);c.name("path_graph("+a+")");c.e(G(cb(a-1),function(a){return[a,a+1]}));return c}y("jsnx.path_graph",Lc);y("jsnx.trivial_graph",function(a){a=Kc(1,a);a.name("null_graph()");return a});y("jsnx.fast_gnp_random_graph",function(a,b,c){c!=m||(c=n);var d=Kc(a);d.name("fast_gnp_random_graph("+a+","+b+")");if(0>=b||1<=b)return Mc(a,b,c);var e=1,f=-1;b=Math.log(1-b);if(c)for(d=Y(d);e<a;){c=Math.log(1-Math.random());f=f+1+Math.floor(c/b);for(e===f&&(f+=1);f>=a&&e<a;)f-=a,e+=1,e==f&&(f+=1);e<a&&d.v(e,f)}else for(;e<a;){c=Math.log(1-Math.random());for(f=f+1+Math.floor(c/b);f>=e&&e<a;)f-=e,e+=1;e<a&&d.v(e,f)}return d});
function Mc(a,b,c){var d;d=c?Y():W();d.m(cb(a));d.name("gnp_random_graph("+a+","+b+")");if(0>=b)return d;if(1<=b)return Jc(a,d);a=d.h()?fb(cb(a)):db(cb(a));F(a,function(a){Math.random()<b&&d.v(a[0],a[1])});return d}y("jsnx.gnp_random_graph",Mc);y("jsnx.binomial_graph",Mc);y("jsnx.erdos_renyi_graph",Mc);y("jsnx.havel_hakimi_graph",function(a,b){lc(a)||h(new T("Invalid degree sequence"));b!=m&&(b.h()&&h(new T("Directed Graph not supported")),b.o()&&h(new T("Havel-Hakimi requires simple graph")));var c=a.length,d=Kc(c,b);if(0===c||0===Math.max.apply(m,a))return d;for(c=H(G(d,function(b){return[a[b],b]}));0<c.length;){c.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:+a[1]-+b[1]});if(0>c[0][0])return n;var e=c.pop();if(0===e[0])break;if(e[0]>c.length)return n;for(var f=c.length,g=f-e[0];g<f;g++)d.v(e[1],
c[g][1]),c[g][0]-=1}d.name("havel_hakimi_graph "+d.Q()+" nodes "+d.size()+" edges");return d});function Nc(a,b,c){var d=b;ka(b)&&(d={},F(a.w(),function(a){d[a]=b(a)}));var e;if(!t(c)||c){var f=d;e=new a.constructor;e.name("("+a.name()+")");a.o()?e.e(G(a.f(l,l),function(a){return[O(f,a[0],a[0]),O(f,a[1],a[1]),a[2],Wa(a[3])]})):e.e(G(a.f(l),function(a){return[O(f,a[0],a[0]),O(f,a[1],a[1]),Wa(a[2])]}));e.m(G(a,function(a){return O(f,a,a)}));c={};for(var g in a.node)c[O(f,g,g)]=Wa(a.node[g]);P(e.node,c);P(e.graph,Wa(a.graph))}else{var k=d;g=new S(M(k));if(0<vb(g,k).c()){g=Y;var q=[];I(k,function(a,
b){q.push([b,a])});g=g(q);g.M(g.oa());try{e=bc.jb.Bb(g)}catch(C){C instanceof Db&&h(new Db("The node label sets are overlapping and no ordering can resolve the mapping. Use copy=True."))}e.reverse()}else e=g;var s=a.o(),D=a.h(),U;F(e,function(b){var c;b in k&&(c=k[b],a.a(b)||h(new T("Node "+b+" is not in the graph.")),a.Z(c,a.node[b]),s?(U=ta(a.I(b,l,l),function(a){return[c,a[1],a[2],a[3]]}),D&&(U=wa(U,ta(a.ia(b,l,l),function(a){return[a[0],c,a[2],a[3]]})))):(U=ta(a.I(b,l),function(a){return[c,a[1],
a[2]]}),D&&(U=wa(U,ta(a.ia(b,l),function(a){return[a[0],c,a[2]]})))),a.sa(b),a.e(U))});e=a}return e}y("jsnx.relabel_nodes",Nc);
y("jsnx.convert_node_labels_to_integers",function(a,b,c,d){3===arguments.length&&ha(c)?(d=c,c=m):2===arguments.length&&(ha(b)?(d=b,b=m):x(b)&&(c=b,b=m));b!=m||(b=0);c!=m||(c="default");d!=m||(d=l);var e={},f,g,k,q;if("default"===c){f=a.nodes();g=0;k=b;for(q=f.length;g<q;g++,k++)e[f[g]]=k}else if("sorted"===c){f=a.nodes();f.sort();g=0;k=b;for(q=f.length;g<q;g++,k++)e[f[g]]=k}else if("increasing degree"===c){f=H(a.B());f.sort(function(a,b){return a[1]-b[1]});g=0;k=b;for(q=f.length;g<q;g++,k++)e[f[g][0]]=
k}else if("decreasing degree"===c){f=H(a.B());f.sort(function(a,b){return b[1]-a[1]});g=0;k=b;for(q=f.length;g<q;g++,k++)e[f[g][0]]=k}else h(new T("Unkown node ordering: "+c));g=Nc(a,e);g.name("("+a.name()+")_with_int_labels");d||(g.node_labels=e);return g});}());
