(function(){function h(a){throw a;}var aa=void 0,j=!0,l=null,m=!1;function ba(a){return function(){return a}}var n,ca=this;function ea(){}
function q(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function r(a){return a!==aa}function fa(a){return a!=l}function ha(a){return"array"==q(a)}function s(a){var b=q(a);return"array"==b||"object"==b&&"number"==typeof a.length}function t(a){return"string"==typeof a}function v(a){return"boolean"==typeof a}function ia(a){return"number"==typeof a}function la(a){return"function"==q(a)}function ma(a){var b=typeof a;return"object"==b&&a!=l||"function"==b}
var na="closure_uid_"+(1E9*Math.random()>>>0),pa=0;function w(a,b){var c=a.split("."),d=ca;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&r(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function qa(a,b){function c(){}c.prototype=b.prototype;a.Ya=b.prototype;a.prototype=new c;a.prototype.constructor=a};var x=Array.prototype,ra=x.indexOf?function(a,b,c){return x.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(t(a))return!t(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},sa=x.forEach?function(a,b,c){x.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ta=x.filter?function(a,b,c){return x.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=t(a)?
a.split(""):a,k=0;k<d;k++)if(k in g){var p=g[k];b.call(c,p,k,a)&&(e[f++]=p)}return e},y=x.map?function(a,b,c){return x.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=t(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};function ua(a,b){var c=ra(a,b);0<=c&&x.splice.call(a,c,1)}function va(a){return x.concat.apply(x,arguments)}function wa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function ya(a,b,c){return 2>=arguments.length?x.slice.call(a,b):x.slice.call(a,b,c)}function za(a,b,c){if(!s(a)||!s(b)||a.length!=b.length)return m;var d=a.length;c=c||Aa;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return m;return j}function Ba(a,b){return a>b?1:a<b?-1:0}function Aa(a,b){return a===b}function Da(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}};var z="StopIteration"in ca?ca.StopIteration:Error("StopIteration");function A(){}A.prototype.next=function(){h(z)};A.prototype.t=function(){return this};function Ea(a){if(a instanceof A)return a;if("function"==typeof a.t)return a.t(m);if(s(a)){var b=0,c=new A;c.next=function(){for(;;){b>=a.length&&h(z);if(b in a)return a[b++];b++}};return c}h(Error("Not implemented"))}
function C(a,b,c){if(s(a))try{sa(a,b,c)}catch(d){d!==z&&h(d)}else{a=Ea(a);try{for(;;)b.call(c,a.next(),aa,a)}catch(e){e!==z&&h(e)}}}function D(a,b,c){var d=Ea(a);a=new A;a.next=function(){for(;;){var a=d.next();return b.call(c,a,aa,d)}};return a}function Fa(a,b,c){var d=c;C(a,function(a){d=b.call(aa,d,a)});return d}function Ka(a){var b=arguments,c=b.length,d=0,e=new A;e.next=function(){try{return d>=c&&h(z),Ea(b[d]).next()}catch(a){return(a!==z||d>=c)&&h(a),d++,this.next()}};return e}
function La(a){if(s(a))return wa(a);a=Ea(a);var b=[];C(a,function(a){b.push(a)});return b}function Ma(a,b){try{return Ea(a).next()}catch(c){return c!=z&&h(c),b}};function Na(){}Na.fa=function(){return Na.ha?Na.ha:Na.ha=new Na};Na.prototype.za=0;Na.fa();var Oa={};function Pa(a){if(!s(a))return m;for(var b=0,c=a.length;b<c;b++)if(window.isNaN(a[b]))return m;return j}w("jsnx.utils.is_list_of_ints",Pa);w("jsnx.utils.cumulative_sum",function(a){var b=0;return D(a,function(a){return b+=a})});w("jsnx.utils.generate_unique_node",function(){return":"+(Na.fa().za++).toString(36)});function E(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ta(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d}function G(a){var b=0,c;for(c in a)b++;return b}function Ua(a){for(var b in a)return b}function H(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function I(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Va(a){for(var b in a)delete a[b]}function J(a,b){b in a&&delete a[b]}function K(a,b,c){return b in a?a[b]:c}
function Wa(a){var b={},c;for(c in a)b[c]=a[c];return b}var Xa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function M(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Xa.length;f++)c=Xa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}
function Ya(a){var b=arguments.length;if(1==b&&ha(arguments[0]))return Ya.apply(l,arguments[0]);b%2&&h(Error("Uneven number of arguments"));for(var c={},d=0;d<b;d+=2)c[arguments[d]]=arguments[d+1];return c};function Za(a){if("function"==typeof a.A)return a.A();if(t(a))return a.split("");if(s(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return H(a)};function $a(a,b){this.f={};this.j=[];var c=arguments.length;if(1<c){c%2&&h(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.aa(a)}n=$a.prototype;n.u=0;n.W=0;n.e=function(){return this.u};n.A=function(){ab(this);for(var a=[],b=0;b<this.j.length;b++)a.push(this.f[this.j[b]]);return a};n.N=function(){return 0==this.u};n.clear=function(){this.f={};this.W=this.u=this.j.length=0};
n.remove=function(a){return Object.prototype.hasOwnProperty.call(this.f,a)?(delete this.f[a],this.u--,this.W++,this.j.length>2*this.u&&ab(this),j):m};function ab(a){if(a.u!=a.j.length){for(var b=0,c=0;b<a.j.length;){var d=a.j[b];Object.prototype.hasOwnProperty.call(a.f,d)&&(a.j[c++]=d);b++}a.j.length=c}if(a.u!=a.j.length){for(var e={},c=b=0;b<a.j.length;)d=a.j[b],Object.prototype.hasOwnProperty.call(e,d)||(a.j[c++]=d,e[d]=1),b++;a.j.length=c}}
n.set=function(a,b){Object.prototype.hasOwnProperty.call(this.f,a)||(this.u++,this.j.push(a),this.W++);this.f[a]=b};n.aa=function(a){var b;a instanceof $a?(ab(a),b=a.j.concat(),a=a.A()):(b=I(a),a=H(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};n.X=function(){return new $a(this)};
n.t=function(a){ab(this);var b=0,c=this.j,d=this.f,e=this.W,f=this,g=new A;g.next=function(){for(;;){e!=f.W&&h(Error("The map has changed since the iterator was created"));b>=c.length&&h(z);var g=c[b++];return a?g:d[g]}};return g};function N(a){this.f=new $a;a&&this.aa(a)}function bb(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[na]||(a[na]=++pa)):b.substr(0,1)+a}n=N.prototype;n.e=function(){return this.f.e()};n.add=function(a){this.f.set(bb(a),a)};n.aa=function(a){a=Za(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};n.remove=function(a){return this.f.remove(bb(a))};n.clear=function(){this.f.clear()};n.N=function(){return this.f.N()};
n.contains=function(a){a=bb(a);return Object.prototype.hasOwnProperty.call(this.f.f,a)};function cb(a,b){for(var c=new N,d=Za(b),e=0;e<d.length;e++){var f=d[e];a.contains(f)&&c.add(f)}return c}function db(a,b){for(var c=a.X(),d=Za(b),e=d.length,f=0;f<e;f++)c.remove(d[f]);return c}n.A=function(){return this.f.A()};n.X=function(){return new N(this)};n.t=function(){return this.f.t(m)};function eb(a){if(a!=l)try{a.clear()}catch(b){h(Error("Input graph is not a jsnx graph type"))}else a=new Oa.Fa;return a}
function fb(a,b,c){var d;if(a.hasOwnProperty("adj"))try{return d=mb(a.adj,b,a.i()),"graph"in a&&"object"===q(a.graph)&&(d.graph=Wa(a.graph)),"node"in a&&"object"===q(a.node)&&(d.node=Ta(a.node,function(a){return Wa(a)})),d}catch(e){h(Error("Input is not a correct jsnx graph"))}if("object"===q(a))try{return mb(a,b,c)}catch(f){try{var g=eb(b);g.h(a);if(g.i()&&!g.c()){var k={};E(a,function(a,b){sa(a,function(a){a in k||g.g(b,a)});k[b]=1})}else{var p=[];E(a,function(a,b){sa(a,function(a){p.push([b,a])})});
g.a(p)}return g}catch(F){h(Error("Input is not known type."))}}if(s(a))try{var u=eb(b);u.a(a);return u}catch(B){h(Error("Input is not valid edge list"))}}w("jsnx.to_networkx_graph",fb);w("jsnx.convert_to_undirected",Oa.La);w("jsnx.convert_to_undirected",Oa.Ka);w("jsnx.to_dict_of_lists",Oa.Za);
function mb(a,b,c){var d=eb(b),e,f;d.h(a);c?d.c()?(d.i()?(e=[],E(a,function(a,b){s(a)&&h(Error());E(a,function(a,c){E(a,function(a,d){e.push([b,c,d,a])})})})):(e=[],E(a,function(a,b){s(a)&&h(Error());E(a,function(a,c){E(a,function(a){e.push([b,c,a])})})})),d.a(e)):d.i()?(f=new N,E(a,function(a,b){s(a)&&h(Error());E(a,function(a,c){f.contains([b,c].toString())||(e=[],E(a,function(a,d){e.push([b,c,d,a])}),d.a(e),f.add([c,b].toString()))})})):(f=new N,E(a,function(a,b){s(a)&&h(Error());E(a,function(a,
c){f.contains([b,c].toString())||(e=[],E(a,function(a){e.push([b,c,a])}),d.a(e),f.add([c,b].toString()))})})):d.i()&&!d.c()?(f=new N,E(a,function(a,b){s(a)&&h(Error());E(a,function(a,c){f.contains([b,c].toString())||(d.g(b,c,a),f.add([c,b].toString()))})})):(e=[],E(a,function(a,b){s(a)&&h(Error());E(a,function(a,c){e.push([b,c,a])})}),d.a(e));return d};function nb(a){this.name="JSNetworkXException";this.message=a}nb.prototype=Error();nb.prototype.constructor=nb;w("jsnx.JSNetworkXException",nb);function P(a){nb.call(this,a);this.name="JSNetworkXError"}qa(P,nb);w("jsnx.JSNetworkXError",P);function ob(a){nb.call(this,a);this.name="JSNetworkXPointlessConcept"}qa(ob,nb);w("jsnx.JSNetworkXPointlessConcept",ob);function pb(a){nb.call(this,a);this.name="JSNetworkXAlgorithmError"}qa(pb,nb);w("jsnx.JSNetworkXAlgorithmError",pb);
function qb(a){pb.call(this,a);this.name="JSNetworkXUnfeasible"}qa(qb,pb);w("jsnx.JSNetworkXUnfeasible",qb);function rb(a){qb.call(this,a);this.name="JSNetworkXNoPath"}qa(rb,qb);w("jsnx.JSNetworkXNoPath",rb);function sb(a){pb.call(this,a);this.name="JSNetworkXUnbounded"}qa(sb,pb);w("jsnx.JSNetworkXUnbounded",sb);function tb(a){return Fa(ub(a),function(a,c){a[c[0]]=c[1];return a},{})}function vb(a){return a instanceof A||la(a.t)}function wb(a){if(t(a)||s(a)||"length"in a)return a.length;if(xb(a))return G(a);h(new TypeError)}function Q(a,b,c,d){v(c)&&(d=c,c=l);if(d){var e=b;b=function(a){e.apply(this,a)}}vb(a)?C(a,b,c):s(a)||t(a)?sa(a,b,c):ma(a)&&Q(I(a),b,c)}w("jsnx.forEach",Q);function R(a,b,c){if(s(a))return y(a,b,c);if(vb(a))return D(a,b,c);if(ma(a))return Ta(a,b,c);h(new TypeError)}
function yb(){var a=arguments,b=a[0];if(s(b))return Da.apply(l,a);if(vb(b)){var b=new A,c=a.length;b.next=function(){for(var b=[],e=0;e<c;e++)b.push(a[e].next());return b};return b}if(ma(b))return Da.apply(l,y(a,I));h(new TypeError)}
function zb(a,b,c){if(0===arguments.length)return[];1===arguments.length?(b=a,a=0,c=1):2===arguments.length?c=1:3===arguments.length&&0===arguments[2]&&h("range() step argument must not be zero");var d=new A,e=0>c,f=a,g;d.next=function(){(e&&f<=b||!e&&f>=b)&&h(z);g=f;f+=c;return g};return d}
function Ab(a){var b=S(a),c=b.length;if(2>c)return new A;var d=S(zb(2));a=new A;a.next=function(){var a=y(d,function(a){return b[a]});this.next=function(){var a=m,e;for(e=2;e--;)if(d[e]!=e+c-2){a=j;break}a||h(z);d[e]+=1;for(a=e+1;2>a;a++)d[a]=d[a-1]+1;return y(d,function(a){return b[a]})};return a};return a}
function Bb(a){var b=S(a),c=b.length,d=ia(2)?2:c;if(d>c)return new A;var e=S(zb(c)),f=S(zb(c,c-d,-1));a=new A;var g=new A,k,p=j;a.next=function(){this.next=k.next;return y(e.slice(0,d),function(a){return b[a]})};g.next=function(){return p};k=T(g,function(a){a||h(z);p=m;return zb(d-1,-1,-1)},function(a){if(!p)if(f[a]-=1,0===f[a])e.splice.apply(e,[a,e.length].concat(e.slice(a+1).concat([e[a]]))),f[a]=c-a;else{var g=f[a],k=e[a];e[a]=e[e.length-g];e[e.length-g]=k;p=j;return ub([y(e.slice(0,d),function(a){return b[a]})])}},
function(a){return a});return a}function Db(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)!r(a[c])||"object"!==q(a[c])?a[c]=U(d[c]):"object"===q(a[c])&&"object"===q(d)&&Db(a[c],d[c]);for(var f=0;f<Xa.length;f++)c=Xa[f],Object.prototype.hasOwnProperty.call(d,c)&&(!r(a[c])||"object"!==q(a[c])?a[c]=U(d[c]):"object"===q(a[c])&&"object"===q(d)&&Db(a[c],d[c]))}}function S(a){if(s(a))return wa(a);if(vb(a))return La(a);if(ma(a))return I(a);h(new TypeError)}w("jsnx.toArray",S);
function Eb(a){var b=[];E(a,function(a,d){b.push([d,a])});return b}function V(a){var b=new A,c=Ea(I(a));b.next=function(){var b=c.next();return[b,a[b]]};return b}function ub(a){"object"===q(a)&&(!s(a)&&!vb(a))&&(a=I(a));return Ea(a)}
function T(a){var b=new A,c=ya(arguments,1);if(0===c.length)return a;try{a=Ea(a)}catch(d){return b.next=function(){"Not implemented"===d.message&&h(new TypeError)},b}var e=l;b.next=function(){var d,g;try{for(;!r(d);)d=e.next()}catch(k){for(;!r(g)||!r(d);)g=a.next(),d=c[0](g);if(vb(d))return e=T.apply(l,va([d],ya(c,1))),b.next();e=l}return d};return b}w("jsnx.sentinelIterator",function(a,b){var c=new A;c.next=function(){return Ma(a,b)};return c});
function xb(a){var b=Object.prototype.hasOwnProperty;if(!a||"object"!==q(a)||a.nodeType||a==a.window)return m;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return m}catch(c){return m}for(var d in a);return d===aa||b.call(a,d)}
function U(a,b){b=b||[];var c=q(a);if("object"==c&&xb(a)||"array"==c){var d;d=b;var e;a:{e=function(b){return a===b[0]};for(var f=d.length,g=t(d)?d.split(""):d,k=0;k<f;k++)if(k in g&&e.call(aa,g[k])){e=k;break a}e=-1}d=0>e?l:t(d)?d.charAt(e):d[e];if(d!==l)return d[1];if(a.X)return d=[a,a.X()],b.push(d),d[1];c="array"==c?[]:{};d=[a,c];b.push(d);for(var p in a)c[p]=U(a[p],b);return c}return a}
function Fb(a){function b(){}var c={},d;b.prototype=a.constructor.prototype;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);c=U(c);a=new b;for(d in c)a[d]=c[d];return a};function Gb(a){var b=[];Hb(new Ib,a,b);return b.join("")}function Ib(){this.$=aa}
function Hb(a,b,c){switch(typeof b){case "string":Jb(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if(ha(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],Hb(a,a.$?a.$.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),Jb(f,c),c.push(":"),
Hb(a,a.$?a.$.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:h(Error("Unknown type: "+typeof b))}}var Kb={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Lb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Jb(a,b){b.push('"',a.replace(Lb,function(a){if(a in Kb)return Kb[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Kb[a]=e+b.toString(16)}),'"')};var W={Ta:function(a){return Math.floor(Math.random()*a)},ab:function(a,b){return a+Math.random()*(b-a)},Ja:function(a,b,c){return Math.min(Math.max(a,b),c)},ya:function(a,b){var c=a%b;return 0>c*b?c+b:c},Qa:function(a,b,c){return a+c*(b-a)},Sa:function(a,b,c){return Math.abs(a-b)<=(c||1E-6)},da:function(a){return W.ya(a,360)},la:function(a){return a*Math.PI/180},Ea:function(a){return 180*a/Math.PI},Ha:function(a,b){return b*Math.cos(W.la(a))},Ia:function(a,b){return b*Math.sin(W.la(a))},ea:function(a,
b,c,d){return W.da(W.Ea(Math.atan2(d-b,c-a)))},Ga:function(a,b){var c=W.da(b)-W.da(a);180<c?c-=360:-180>=c&&(c=360+c);return c},Wa:function(a){return 0==a?0:0>a?-1:1},Ra:function(a,b,c,d){c=c||function(a,b){return a==b};d=d||function(b){return a[b]};for(var e=a.length,f=b.length,g=[],k=0;k<e+1;k++)g[k]=[],g[k][0]=0;for(var p=0;p<f+1;p++)g[0][p]=0;for(k=1;k<=e;k++)for(p=1;p<=e;p++)g[k][p]=c(a[k-1],b[p-1])?g[k-1][p-1]+1:Math.max(g[k-1][p],g[k][p-1]);for(var F=[],k=e,p=f;0<k&&0<p;)c(a[k-1],b[p-1])?(F.unshift(d(k-
1,p-1)),k--,p--):g[k-1][p]>g[k][p-1]?k--:p--;return F},o:function(a){var b;b=arguments;var c=function(a,b){return a+b};if(b.reduce)b=b.reduce(c,0);else{var d=0;sa(b,function(a){d=c.call(aa,d,a)});b=d}return b},sa:function(a){return W.o.apply(l,arguments)/arguments.length},Xa:function(a){var b=arguments.length;if(2>b)return 0;var c=W.sa.apply(l,arguments),b=W.o.apply(l,y(arguments,function(a){return Math.pow(a-c,2)}))/(b-1);return Math.sqrt(b)},Pa:function(a){return isFinite(a)&&0==a%1},Oa:function(a){return isFinite(a)&&
!isNaN(a)},Va:function(a,b){return Math.floor(a+(b||2E-15))},Ua:function(a,b){return Math.ceil(a-(b||2E-15))}};function X(a,b){if(!(this instanceof X))return new X(a,b);this.graph={};this.node={};this.adj={};a!=l&&fb(a,this);M(this.graph,b||{});this.edge=this.adj}w("jsnx.classes.Graph",X);w("jsnx.Graph",X);X.__name__="Graph";X.prototype.va=l;X.prototype.graph=X.prototype.va;X.prototype.Y=function(a){return this.Y[a.toString()]};X.prototype.node=X.prototype.Y;X.prototype.qa=l;X.prototype.adj=X.prototype.qa;X.prototype.ta=l;X.prototype.edge=X.prototype.ta;
X.prototype.name=function(a){if(r(a))this.graph.name=a.toString();else return this.graph.name||""};X.prototype.name=X.prototype.name;X.prototype.toString=function(){return this.name()};X.prototype.toString=X.prototype.toString;X.prototype.t=function(){return ub(this.adj)};X.prototype.__iterator__=X.prototype.t;X.prototype.l=function(a){a in this.adj||h({name:"KeyError",message:"Graph does not contain node "+a+"."});return this.adj[a]};X.prototype.get_node=X.prototype.l;
X.prototype.F=function(a,b){b!=l||(b={});"object"!==q(b)&&h(new P("The attr_dict argument must be an object."));a in this.adj?M(this.node[a],b||{}):(this.adj[a]={},this.node[a]=b||{})};X.prototype.add_node=X.prototype.F;X.prototype.h=function(a,b){var c,d,e,f,g;b=b||{};Q(a,function(a){c=!(a in this.adj);ha(a)?(d=a[0],e=a[1],d in this.adj?(g=this.node[d],M(g,b,e)):(this.adj[d]={},f=Wa(b),M(f,e),this.node[d]=f)):c?(this.adj[a]={},this.node[a]=Wa(b)):M(this.node[a],b)},this)};
X.prototype.add_nodes_from=X.prototype.h;X.prototype.J=function(a){var b=this.adj,c;a in this.node||h(new P("The node "+a+" is not in the graph"));c=I(b[a]);J(this.node,a);sa(c,function(c){J(b[c],a)});J(b,a)};X.prototype.remove_node=X.prototype.J;X.prototype.T=function(a){var b=this.adj;Q(a,function(a){try{J(this.node,a),E(b[a],function(d,f){J(b[f],a)}),J(b,a)}catch(d){}},this)};X.prototype.remove_nodes_from=X.prototype.T;X.prototype.H=function(a){return a?V(this.node):ub(I(this.adj))};
X.prototype.nodes_iter=X.prototype.H;X.prototype.nodes=function(a){return La(this.H(a))};X.prototype.nodes=X.prototype.nodes;X.prototype.R=function(){return G(this.adj)};X.prototype.number_of_nodes=X.prototype.R;X.prototype.v=function(){return G(this.adj)};X.prototype.order=X.prototype.v;X.prototype.k=function(a){return!ha(a)&&a in this.adj};X.prototype.has_node=X.prototype.k;
X.prototype.g=function(a,b,c){c=c||{};"object"!==q(c)&&h(new P("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});var d=K(this.adj[a],b,{});M(d,c);this.adj[a][b]=d;this.adj[b][a]=d};X.prototype.add_edge=X.prototype.g;
X.prototype.a=function(a,b){b=b||{};"object"!==q(b)&&h(new P("The attr_dict argument must be an object."));Q(a,function(a){var d=wb(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new P("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.adj||(this.adj[e]={},this.node[e]={});f in this.adj||(this.adj[f]={},this.node[f]={});a=K(this.adj[e],f,{});M(a,b,g);this.adj[e][f]=a;this.adj[f][e]=a},this)};X.prototype.add_edges_from=X.prototype.a;
X.prototype.pa=function(a,b,c){c=c||{};t(b)||(c=b,b="weight");this.a(R(a,function(a){var c={};c[b]=a[2];r(c[b])||h(new TypeError("Values must consist of three elements: "+Gb(a)));return[a[0],a[1],c]}),c)};X.prototype.add_weighted_edges_from=X.prototype.pa;X.prototype.s=function(a,b){try{J(this.adj[a],b),a!=b&&J(this.adj[b],a)}catch(c){c instanceof TypeError&&h(new P("The edge "+a+"-"+b+" is not in the graph")),h(c)}};X.prototype.remove_edge=X.prototype.s;
X.prototype.w=function(a){Q(a,function(a){var c=a[0];a=a[1];c in this.adj&&a in this.adj[c]&&(J(this.adj[c],a),c!=a&&J(this.adj[a],c))},this)};X.prototype.remove_edges_from=X.prototype.w;X.prototype.B=function(a,b){return a in this.adj&&b in this.adj[a]};X.prototype.has_edge=X.prototype.B;X.prototype.Q=function(a){a in this.adj||h(new P("The node "+a+" is not in the graph."));return S(this.adj[a])};X.prototype.neighbors=X.prototype.Q;
X.prototype.ba=function(a){a in this.adj||h(new P("The node "+a+" is not in the graph."));return ub(this.adj[a])};X.prototype.neighbors_iter=X.prototype.ba;X.prototype.q=function(a,b){return S(this.d(a,b))};X.prototype.edges=X.prototype.q;
X.prototype.d=function(a,b){v(a)&&(b=a,a=l);var c={},d,e;d=a!=l?R(this.b(a),function(a){return[a,this.adj[a]]},this):V(this.adj);return b?T(d,function(a){e=a[0];var b=new A,d=V(a[1]);b.next=function(){try{return d.next()}catch(a){a===z&&(c[e]=1),h(a)}};return b},function(a){if(!(a[0]in c))return[e,a[0],a[1]]}):T(d,function(a){e=a[0];var b=new A,d=ub(a[1]);b.next=function(){try{return d.next()}catch(a){a===z&&(c[e]=1),h(a)}};return b},function(a){if(!(a in c))return[e,a]})};
X.prototype.edges_iter=X.prototype.d;X.prototype.K=function(a,b,c){r(c)||(c=l);return a in this.adj?K(this.adj[a],b,c):c};X.prototype.get_edge_data=X.prototype.K;X.prototype.ra=function(){return S(R(this.p(),function(a){return I(a[1])}))};X.prototype.adjacency_list=X.prototype.ra;X.prototype.p=function(){return V(this.adj)};X.prototype.adjacency_iter=X.prototype.p;X.prototype.m=function(a,b){return this.k(a)?this.n(a,b).next()[1]:tb(La(this.n(a,b)))};X.prototype.degree=X.prototype.m;
X.prototype.n=function(a,b){var c;c=a!=l?R(this.b(a),function(a){return[a,this.adj[a]]},this):V(this.adj);return b?R(c,function(a){var c=a[0];a=a[1];var f=0,g;for(g in a)f+=+K(a[g],b,1);f+=+(c in a&&K(a[c],b,1));return[c,f]}):R(c,function(a){return[a[0],G(a[1])+ +(a[0]in a[1])]})};X.prototype.degree_iter=X.prototype.n;X.prototype.clear=function(){this.name("");Va(this.adj);Va(this.node);Va(this.graph)};X.prototype.clear=X.prototype.clear;X.prototype.copy=function(){return Fb(this)};
X.prototype.copy=X.prototype.copy;X.prototype.i=ba(m);X.prototype.is_multigraph=X.prototype.i;X.prototype.c=ba(m);X.prototype.is_directed=X.prototype.c;X.prototype.D=function(){var a=new Y;a.name(this.name());a.h(this);a.a(function(){var a;return T(this.p(),function(c){a=c[0];return V(c[1])},function(c){return[a,c[0],U(c[1])]})}.call(this));a.graph=U(this.graph);a.node=U(this.node);return a};X.prototype.to_directed=X.prototype.D;X.prototype.V=function(){return Fb(this)};
X.prototype.to_undirected=X.prototype.V;X.prototype.z=function(a){a=this.b(a);var b=new this.constructor,c=b.adj,d=this.adj;Q(a,function(a){var b={};c[a]=b;E(d[a],function(d,k){k in c&&(b[k]=d,c[k][a]=d)})});Q(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};X.prototype.subgraph=X.prototype.z;X.prototype.Aa=function(){return y(ta(Eb(this.adj),function(a){return a[0]in a[1]}),function(a){return a[0]})};X.prototype.nodes_with_selfloops=X.prototype.Aa;
X.prototype.U=function(a){return a?y(ta(Eb(this.adj),function(a){return a[0]in a[1]}),function(a){var c=a[0];return[c,c,a[1][c]]}):y(ta(Eb(this.adj),function(a){return a[0]in a[1]}),function(a){return[a[0],a[0]]})};X.prototype.selfloop_edges=X.prototype.U;X.prototype.Ba=function(){return this.U().length};X.prototype.number_of_selfloops=X.prototype.Ba;X.prototype.size=function(a){var b=W.o.apply(l,H(this.m(l,a)))/2;return a!=l?b:Math.floor(b)};X.prototype.size=X.prototype.size;
X.prototype.I=function(a,b){return a==l?Math.floor(this.size()):b in this.adj[a]?1:0};X.prototype.number_of_edges=X.prototype.I;X.prototype.oa=function(a,b){var c=S(a),d=c[0],c=R(ya(c,1),function(a){return[d,a]});this.a(c,b)};X.prototype.add_star=X.prototype.oa;X.prototype.na=function(a,b){var c=S(a),c=Da(ya(c,0,c.length-1),ya(c,1));this.a(c,b)};X.prototype.add_path=X.prototype.na;X.prototype.ma=function(a,b){var c=S(a),c=Da(c,va(ya(c,1),[c[0]]));this.a(c,b)};X.prototype.add_cycle=X.prototype.ma;
X.prototype.b=function(a){if(a!=l)if(this.k(a))a=ub([a.toString()]);else{var b=this.adj,c=new A,d=T(a,function(a){if(a in b)return a.toString()});c.next=function(){try{return d.next()}catch(a){a instanceof TypeError&&h(new P("nbunch is not a node or a sequence of nodes")),h(a)}};a=c}else a=ub(this.adj);return a};X.prototype.nbunch_iter=X.prototype.b;function Y(a,b){if(!(this instanceof Y))return new Y(a,b);this.graph={};this.node={};this.adj={};this.pred={};this.succ=this.adj;a!=l&&fb(a,this);M(this.graph,b||{});this.edge=this.adj}w("jsnx.classes.DiGraph",Y);w("jsnx.DiGraph",Y);qa(Y,X);Y.__name__="DiGraph";Y.prototype.F=function(a,b){b!=l||(b={});"object"!==q(b)&&h(new P("The attr_dict argument must be an object."));a in this.succ?M(this.node[a],b):(this.succ[a]={},this.pred[a]={},this.node[a]=b)};Y.prototype.add_node=Y.prototype.F;
Y.prototype.h=function(a,b){var c,d,e,f,g;b=b||{};Q(ub(a),function(a){c=!(a in this.succ);ha(a)?(d=a[0],e=a[1],d in this.succ?(g=this.node[d],M(g,b,e)):(this.succ[d]={},this.pred[d]={},f=Wa(b),M(f,e),this.node[d]=f)):c?(this.succ[a]={},this.pred[a]={},this.node[a]=Wa(b)):M(this.node[a],b)},this)};Y.prototype.add_nodes_from=Y.prototype.h;
Y.prototype.J=function(a){a in this.node||h(new P("The node "+a+" is not in the graph"));var b=this.succ[a];J(this.node,a);E(b,function(b,d){J(this.pred[d],a)},this);J(this.succ,a);E(this.pred[a],function(b,d){J(this.succ[d],a)},this);J(this.pred,a)};Y.prototype.remove_node=Y.prototype.J;
Y.prototype.T=function(a){var b;Q(a,function(a){a in this.succ&&(b=this.succ[a],J(this.node,a),E(b,function(b,e){J(this.pred[e],a)},this),J(this.succ,a),E(this.pred[a],function(b,e){J(this.succ[e],a)},this),J(this.pred,a))},this)};Y.prototype.remove_nodes_from=Y.prototype.T;
Y.prototype.g=function(a,b,c){c=c||{};"object"!==q(c)&&h(new P("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});var d=K(this.adj[a],b,{});M(d,c);this.succ[a][b]=d;this.pred[b][a]=d};Y.prototype.add_edge=Y.prototype.g;
Y.prototype.a=function(a,b){b=b||{};"object"!==q(b)&&h(new P("The attr_dict argument must be an object."));Q(a,function(a){var d=wb(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new P("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.succ||(this.succ[e]={},this.pred[e]={},this.node[e]={});f in this.succ||(this.succ[f]={},this.pred[f]={},this.node[f]={});a=K(this.adj[e],f,{});M(a,b,g);this.succ[e][f]=a;this.pred[f][e]=a},this)};
Y.prototype.add_edges_from=Y.prototype.a;Y.prototype.s=function(a,b){try{J(this.succ[a],b),J(this.pred[b],a)}catch(c){c instanceof TypeError&&h(new P("The edge "+a+"-"+b+" is not in the graph")),h(c)}};Y.prototype.remove_edge=Y.prototype.s;Y.prototype.w=function(a){Q(a,function(a){var c=a[0];a=a[1];c in this.succ&&a in this.succ[c]&&(J(this.succ[c],a),J(this.pred[a],c))},this)};Y.prototype.remove_edges_from=Y.prototype.w;Y.prototype.xa=function(a,b){return a in this.succ&&b in this.succ[a]};
Y.prototype.has_successor=Y.prototype.xa;Y.prototype.wa=function(a,b){return a in this.pred&&b in this.pred[a]};Y.prototype.has_predecessor=Y.prototype.wa;Y.prototype.ka=function(a){a in this.succ||h(new P("The node "+a+" is not in the digraph."));return ub(this.succ[a])};Y.prototype.successors_iter=Y.prototype.ka;Y.prototype.Da=function(a){a in this.pred||h(new P("The node "+a+" is not in the digraph."));return ub(this.pred[a])};Y.prototype.predecessors_iter=Y.prototype.Da;
Y.prototype.ja=function(a){a in this.succ||h(new P("The node "+a+" is not in the digraph."));return S(this.succ[a])};Y.prototype.successors=Y.prototype.ja;Y.prototype.Ca=function(a){a in this.succ||h(new P("The node "+a+" is not in the digraph."));return S(this.pred[a])};Y.prototype.predecessors=Y.prototype.Ca;Y.prototype.Q=Y.prototype.ja;Y.prototype.neighbors=Y.prototype.Q;Y.prototype.ba=Y.prototype.ka;Y.prototype.neighbors_iter=Y.prototype.ba;
Y.prototype.d=function(a,b){v(a)&&(b=a,a=l);var c,d,e;c=a!=l?R(this.b(a),function(a){return[a,this.adj[a]]},this):Eb(this.adj);return b?T(c,function(a){d=a[0];e=a[1];return V(e)},function(a){return[d,a[0],a[1]]}):T(c,function(a){d=a[0];e=a[1];return V(e)},function(a){return[d,a[0]]})};Y.prototype.edges_iter=Y.prototype.d;Y.prototype.Z=Y.prototype.d;Y.prototype.out_edges_iter=Y.prototype.Z;Y.prototype.ca=X.prototype.q;Y.prototype.out_edges=Y.prototype.ca;
Y.prototype.C=function(a,b){v(a)&&(b=a,a=l);var c,d;c=a!=l?R(this.b(a),function(a){return[a,this.pred[a]]},this):Eb(this.pred);return b?T(c,function(a){d=a[0];return V(a[1])},function(a){return[a[0],d,a[1]]}):T(c,function(a){d=a[0];return V(a[1])},function(a){return[a[0],d]})};Y.prototype.in_edges_iter=Y.prototype.C;Y.prototype.M=function(a,b){return S(this.C(a,b))};Y.prototype.in_edges=Y.prototype.M;
Y.prototype.n=function(a,b){var c;c=a!=l?yb(R(this.b(a),function(a){return[a,this.succ[a]]},this),R(this.b(a),function(a){return[a,this.pred[a]]},this)):yb(V(this.succ),V(this.pred));return b?R(c,function(a){var c=a[0][1],f=a[1][1],g=0,k;for(k in c)g+=+K(c[k],b,1);for(k in f)g+=+K(f[k],b,1);return[a[0][0],g]}):R(c,function(a){return[a[0][0],wb(a[0][1])+wb(a[1][1])]})};Y.prototype.degree_iter=Y.prototype.n;
Y.prototype.L=function(a,b){var c;c=a!=l?R(this.b(a),function(a){return[a,this.pred[a]]},this):V(this.pred);return b?R(c,function(a){var c=0,f=a[1],g;for(g in f)c+=+K(f[g],b,1);return[a[0],c]}):R(c,function(a){return[a[0],G(a[1])]})};Y.prototype.in_degree_iter=Y.prototype.L;Y.prototype.S=function(a,b){var c;c=a!=l?R(this.b(a),function(a){return[a,this.succ[a]]},this):V(this.succ);return b?R(c,function(a){var c=0,f=a[1],g;for(g in f)c+=+K(f[g],b,1);return[a[0],c]}):R(c,function(a){return[a[0],G(a[1])]})};
Y.prototype.out_degree_iter=Y.prototype.S;Y.prototype.ga=function(a,b){return this.k(a)?this.L(a,b).next()[1]:tb(this.L(a,b))};Y.prototype.in_degree=Y.prototype.ga;Y.prototype.ia=function(a,b){return this.k(a)?this.S(a,b).next()[1]:tb(this.S(a,b))};Y.prototype.out_degree=Y.prototype.ia;Y.prototype.clear=function(){Va(this.succ);Va(this.pred);Va(this.node);Va(this.graph)};Y.prototype.clear=Y.prototype.clear;Y.prototype.i=ba(m);Y.prototype.is_multigraph=Y.prototype.i;Y.prototype.c=ba(j);
Y.prototype.is_directed=Y.prototype.c;Y.prototype.D=function(){return Fb(this)};Y.prototype.to_directed=Y.prototype.D;Y.prototype.V=function(a){var b=new X;b.name(this.name());b.h(this);var c=this.pred,d;a?b.a(T(this.p(),function(a){d=a[0];return V(a[1])},function(a){if(a[0]in c[d])return[d,a[0],U(a[1])]})):b.a(T(this.p(),function(a){d=a[0];return V(a[1])},function(a){return[d,a[0],U(a[1])]}));b.graph=U(this.graph);b.node=U(this.node);return b};Y.prototype.to_undirected=Y.prototype.V;
Y.prototype.reverse=function(a){(a=!r(a)||a)?(a=new this.constructor(l,{name:"Reverse of ("+this.name()+")"}),a.h(this),a.a(R(this.d(j),function(a){return[a[1],a[0],U(a[2])]})),a.graph=U(this.graph),a.node=U(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};Y.prototype.reverse=Y.prototype.reverse;
Y.prototype.z=function(a){a=this.b(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;Q(a,function(a){c[a]={};d[a]={}});Q(c,function(a){var b=c[a];E(e[a],function(e,p){p in c&&(b[p]=e,d[p][a]=e)})});Q(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};Y.prototype.subgraph=Y.prototype.z;function Z(a,b){if(!(this instanceof Z))return new Z(a,b);X.call(this,a,b)}qa(Z,X);w("jsnx.classes.MultiGraph",Z);w("jsnx.MultiGraph",Z);Z.__name__="MultiGraph";
Z.prototype.g=function(a,b,c,d){var e,f;c!=l&&(!t(c)&&!ia(c))&&(d=c,c=l);d=d||{};"object"!==q(d)&&h(new P("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});if(b in this.adj[a]){f=this.adj[a][b];if(c==l)for(c=G(f);c in f;)c+=1;e=K(f,c,{});M(e,d);f[c]=e}else c!=l||(c=0),e={},M(e,d),f=Ya(c,e),this.adj[a][b]=f,this.adj[b][a]=f};Z.prototype.add_edge=Z.prototype.g;
Z.prototype.a=function(a,b){b=b||{};"object"!==q(b)&&h(new P("The attr_dict argument must be an object."));Q(a,function(a){var d=wb(a),e,f,g=l,k={};4===d?(e=a[0],f=a[1],g=a[2],k=a[3]):3===d?(e=a[0],f=a[1],k=a[2]):2===d?(e=a[0],f=a[1]):h(new P("Edge tuple "+Gb(a)+" must be a 2-tuple, 3-tuple or 4-tuple."));a=e in this.adj?K(this.adj[e],f,{}):{};if(g==l)for(g=G(a);g in a;)g+=1;a=K(a,g,{});M(a,b,k);this.g(e,f,g,a)},this)};Z.prototype.add_edges_from=Z.prototype.a;
Z.prototype.s=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&h(new P("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];c!=l?(c in d||h(new P("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),J(d,c)):J(d,Ua(d));0===G(d)&&(J(this.adj[a],b),a!=b&&J(this.adj[b],a))};Z.prototype.remove_edge=Z.prototype.s;Z.prototype.w=function(a){Q(a,function(a){try{this.s(a[0],a[1],a[2])}catch(c){c instanceof P||h(c)}},this)};Z.prototype.remove_edges_from=Z.prototype.w;
Z.prototype.B=function(a,b,c){return c!=l?a in this.adj&&b in this.adj[a]&&c in this.adj[a][b]:a in this.adj&&b in this.adj[a]};Z.prototype.has_edge=Z.prototype.B;Z.prototype.q=function(a,b,c){return La(this.d(a,b,c))};Z.prototype.edges=Z.prototype.q;
Z.prototype.d=function(a,b,c){v(a)&&(v(b)&&(c=b),b=a,a=l);var d={},e,f;a=a!=l?R(this.b(a),function(a){return[a,this.adj[a]]},this):V(this.adj);return b?T(a,function(a){e=a[0];var b=new A,c=V(a[1]);b.next=function(){try{return c.next()}catch(a){a===z&&(d[e]=1),h(a)}};return b},function(a){f=a[0];if(!(f in d))return V(a[1])},function(a){return c?[e,f,a[0],a[1]]:[e,f,a[1]]}):T(a,function(a){e=a[0];var b=new A,c=V(a[1]);b.next=function(){try{return c.next()}catch(a){a===z&&(d[e]=1),h(a)}};return b},function(a){f=
a[0];if(!(f in d))return V(a[1])},function(a){return c?[e,f,a[0]]:[e,f]})};Z.prototype.edges_iter=Z.prototype.d;Z.prototype.K=function(a,b,c,d){r(d)||(d=l);return a in this.adj&&b in this.adj[a]?c!=l?K(this.adj[a][b],c,d):this.adj[a][b]:d};Z.prototype.get_edge_data=Z.prototype.K;
Z.prototype.n=function(a,b){var c;c=a!=l?R(this.b(a),function(a){return[a,this.adj[a]]},this):V(this.adj);return b!=l?D(c,function(a){var c=a[0];a=a[1];var f=0;E(a,function(a){E(a,function(a){f+=K(a,b,1)})});c in a&&E(a[c],function(a){f+=K(a,b,1)});return[c,f]}):D(c,function(a){var b=a[0];a=a[1];var c=0;E(a,function(a){c+=G(a)});return[b,c+ +(b in a&&G(a[b]))]})};Z.prototype.degree_iter=Z.prototype.n;Z.prototype.i=ba(j);Z.prototype.is_multigraph=Z.prototype.i;Z.prototype.c=ba(m);
Z.prototype.is_directed=Z.prototype.c;Z.prototype.D=function(){var a=new $;a.h(this);a.a(function(){var a,c;return T(this.p(),function(c){a=c[0];return V(c[1])},function(a){c=a[0];return V(a[1])},function(d){return[a,c,d[0],U(d[1])]})}.call(this));a.graph=U(this.graph);a.node=U(this.node);return a};Z.prototype.to_directed=Z.prototype.D;
Z.prototype.U=function(a,b){var c=[];a?b?E(this.adj,function(a,b){b in a&&E(a[b],function(a,d){c.push([b,b,d,a])})}):E(this.adj,function(a,b){b in a&&E(a[b],function(a){c.push([b,b,a])})}):b?E(this.adj,function(a,b){b in a&&E(a[b],function(a,d){c.push([b,b,d])})}):E(this.adj,function(a,b){b in a&&E(a[b],function(){c.push([b,b])})});return c};Z.prototype.selfloop_edges=Z.prototype.U;Z.prototype.I=function(a,b){return a==l?this.size():a in this.adj&&b in this.adj[a]?G(this.adj[a][b]):0};
Z.prototype.number_of_edges=Z.prototype.I;Z.prototype.z=function(a){a=this.b(a);var b=new this.constructor,c=b.adj,d=this.adj;C(a,function(a){var b={};c[a]=b;E(d[a],function(d,k){if(k in c){var p=Wa(d);b[k]=p;c[k][a]=p}})});E(this.node,function(a,c){b.node[c]=a});b.graph=this.graph;return b};Z.prototype.subgraph=Z.prototype.z;function $(a,b){if(!(this instanceof $))return new $(a,b);Y.call(this,a,b)}qa($,Y);var Mb=$.prototype,Nb=Z.prototype,Ob;for(Ob in Nb)Nb.hasOwnProperty(Ob)&&"constructor"!==Ob&&(Mb[Ob]=Nb[Ob]);w("jsnx.classes.MultiDiGraph",$);w("jsnx.MultiDiGraph",$);$.__name__="MultiDiGraph";
$.prototype.g=function(a,b,c,d){var e,f;c!=l&&(!t(c)&&!ia(c))&&(d=c,c=l);d=d||{};"object"!==q(d)&&h(new P("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});if(b in this.succ[a]){f=this.adj[a][b];if(c==l)for(c=G(f);c in f;)c+=1;e=K(f,c,{});M(e,d);f[c]=e}else c!=l||(c=0),e={},M(e,d),f=Ya(c,e),this.succ[a][b]=f,this.pred[b][a]=f};$.prototype.add_edge=$.prototype.g;
$.prototype.s=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&h(new P("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];c!=l?(c in d||h(new P("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),J(d,c)):J(d,Ua(d));0===G(d)&&(J(this.succ[a],b),J(this.pred[b],a))};$.prototype.remove_edge=$.prototype.s;
$.prototype.d=function(a,b,c){v(a)&&(v(b)&&(c=b),b=a,a=l);var d,e;a=a!=l?R(this.b(a),function(a){return[a,this.adj[a]]},this):Eb(this.adj);return b?T(a,function(a){d=a[0];return V(a[1])},function(a){e=a[0];return V(a[1])},function(a){return c?[d,e,a[0],a[1]]:[d,e,a[1]]}):T(a,function(a){d=a[0];return V(a[1])},function(a){e=a[0];return V(a[1])},function(a){return c?[d,e,a[0]]:[d,e]})};$.prototype.edges_iter=$.prototype.d;$.prototype.Z=$.prototype.d;$.prototype.out_edges_iter=$.prototype.Z;
$.prototype.ca=function(a,b,c){return La(this.Z(a,b,c))};$.prototype.out_edges=$.prototype.ca;$.prototype.C=function(a,b,c){v(a)&&(b=a,a=l);var d,e;a=fa?R(this.b(a),function(a){return[a,this.pred[a]]},this):Eb(this.pred);return b?T(a,function(a){d=a[0];return V(a[1])},function(a){e=a[0];return V(a[1])},function(a){return c?[e,d,a[0],a[1]]:[e,d,a[1]]}):T(a,function(a){d=a[0];return V(a[1])},function(a){e=a[0];return V(a[1])},function(a){return c?[e,d,a[0]]:[e,d]})};$.prototype.in_edges_iter=$.prototype.C;
$.prototype.M=function(a,b,c){return La(this.C(a,b,c))};$.prototype.in_edges=$.prototype.M;
$.prototype.n=function(a,b){var c;c=a!=l?yb(D(this.b(a),function(a){return[a,this.succ[a]]},this),D(this.b(a),function(a){return[a,this.pred[a]]},this)):yb(V(this.succ),V(this.pred));return b!=l?R(c,function(a){var c=a[0][1],f=0;E(a[1][1],function(a){E(a,function(a){f+=+K(a,b,1)})});E(c,function(a){E(a,function(a){f+=+K(a,b,1)})});return[a[0][0],f]}):R(c,function(a){var b=0,c=0;E(a[1][1],function(a){b+=wb(a)});E(a[0][1],function(a){c+=wb(a)});return[a[0][0],b+c]})};$.prototype.degree_iter=$.prototype.n;
$.prototype.L=function(a,b){var c;c=a!=l?R(this.b(a),function(a){return[a,this.pred[a]]},this):V(this.pred);return b!=l?R(c,function(a){var c=0;E(a[1],function(a){E(a,function(a){c+=+K(a,b,1)})});return[a[0][0],c]}):R(c,function(a){var b=0;E(a[1],function(a){b+=G(a)});return[a[0],b]})};$.prototype.in_degree_iter=$.prototype.L;
$.prototype.S=function(a,b){var c;c=a!=l?R(this.b(a),function(a){return[a,this.succ[a]]},this):V(this.succ);return b!=l?R(c,function(a){var c=0;E(a[1],function(a){E(a,function(a){c+=+K(a,b,1)})});return[a[0][0],c]}):R(c,function(a){var b=0;E(a[1],function(a){b+=G(a)});return[a[0],b]})};$.prototype.out_degree_iter=$.prototype.S;$.prototype.i=ba(j);$.prototype.is_multigraph=$.prototype.i;$.prototype.c=ba(j);$.prototype.is_directed=$.prototype.c;$.prototype.D=function(){return Fb(this)};
$.prototype.to_directed=$.prototype.D;$.prototype.V=function(a){var b=new Z;b.name(this.name());b.h(this);var c=this,d,e;a?b.a(T(this.p(),function(a){d=a[0];return V(a[1])},function(a){e=a[0];return V(a[1])},function(a){if(c.B(e,d,a[0]))return[d,e,a[0],U(a[1])]})):b.a(T(this.p(),function(a){d=a[0];return V(a[1])},function(a){e=a[0];return V(a[1])},function(a){return[d,e,a[0],U(a[1])]}));b.graph=U(this.graph);b.node=U(this.node);return b};$.prototype.to_undirected=$.prototype.V;
$.prototype.z=function(a){a=this.b(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;C(a,function(a){c[a]={};d[a]={}});Q(c,function(a){var b=c[a];E(e[a],function(e,p){if(p in c){var F=Wa(e);b[p]=F;d[p][a]=F}})});Q(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};$.prototype.subgraph=$.prototype.z;
$.prototype.reverse=function(a){(a=!r(a)||a)?(a=new this.constructor(l,{name:"Reverse of ("+this.name()+")"}),a.h(this),a.a(D(this.d(j,j),function(a){return[a[1],a[0],a[2],U(a[3])]})),a.graph=U(this.graph),a.node=U(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};$.prototype.reverse=$.prototype.reverse;w("jsnx.nodes",function(a){return a.nodes()});w("jsnx.nodes_iter",function(a){return a.H()});w("jsnx.edges",function(a,b){return a.q(b)});w("jsnx.edges_iter",function(a,b){return a.d(b)});w("jsnx.degree",function(a,b,c){return a.m(b,c)});w("jsnx.neighbors",function(a,b){return a.Q(b)});w("jsnx.number_of_nodes",function(a){return a.R()});w("jsnx.number_of_edges",function(a){return a.I()});w("jsnx.density",function(a){var b=a.R(),c=a.I();return 0===c?0:a.c()?c/(b*(b-1)):2*c/(b*(b-1))});
w("jsnx.degree_histogram",function(a){a=H(a.m());for(var b=Math.max.apply(Math,a)+1,c=[],d=0;d<b;d++)c[d]=0;sa(a,function(a){c[a]+=1});return c});w("jsnx.is_directed",function(a){return a.c()});w("jsnx.freeze",function(a){function b(){h(new P("Frozen graph can't be modified"))}a.F=b;a.h=b;a.J=b;a.T=b;a.g=b;a.a=b;a.s=b;a.w=b;a.clear=b;a.ua=j;return a});w("jsnx.is_frozen",function(a){return!!a.ua});w("jsnx.subgraph",function(a,b){return a.z(b)});
w("jsnx.create_empty_copy",function(a,b){r(b)||(b=j);var c=new a.constructor;b&&c.h(a);return c});
w("jsnx.info",function(a,b){var c="";if(b!=l)a.k(b)||h(new P("node "+b+" not in graph")),c=c+("Node "+b+" has the following properties:\n")+("Degree: "+a.m(b)+"\n"),c+="Neighbors: "+a.Q(b).join(" ");else{var c=c+("Name: "+a.name()+"\n"),c=c+("Type: "+a.constructor.__name__+"\n"),c=c+("Number of nodes: "+a.R()+"\n"),c=c+("Number of edges: "+a.I()+"\n"),d=a.R();if(0<d)if(a.c())c+="Average in degree: "+(W.o.apply(l,H(a.ga()))/d).toFixed(4)+"\n",c+="Average out degree: "+(W.o.apply(l,H(a.ia()))/d).toFixed(4);
else var e=W.o.apply(l,H(a.m())),c=c+("Average degree: "+(e/d).toFixed(4))}return c});w("jsnx.set_node_attributes",function(a,b,c){E(c,function(c,e){a.Y[e][b]=c})});function Pb(a,b){var c={};E(a.Y,function(a,e){b in a&&(c[e]=a[b])});return c}w("jsnx.get_node_attributes",Pb);w("jsnx.set_edge_attributes",function(a,b,c){E(c,function(b,c){c=c.split(",");a.l(c[0])[c[1]]=b})});Pb=function(a,b){var c={};E(a.q(j),function(a){b in a[2]&&(c[[a[0],a[1]]]=a[2][b])});return c};w("jsnx.get_edge_attributes",{}.Na);var Qb={};function Rb(a,b){a.c()&&h(new P("triangles() is not defined for directed graphs."));if(a.k(b))return Math.floor(Sb(a,b).next()[2]/2);var c={};C(Sb(a,b),function(a){c[a[0]]=Math.floor(a[2]/2)});return c}w("jsnx.triangles",Rb);
function Sb(a,b){a.i()&&h(new P("Not defined for multigraphs."));var c;c=b!=l?T(a.b(b),function(b){return[b,a.l(b)]}):V(a.adj);return D(c,function(b){var c=new N(I(b[1])),f=0;c.remove(b[0]);C(c,function(b){var d=new N(I(a.l(b)));d.remove(b);f+=cb(c,d).e()});return[b[0],c.e(),f]})}
w("jsnx.average_clustering",function(a,b,c,d){2===arguments.length?t(b)?(c=b,b=l):v(b)&&(d=b,b=l):3===arguments.length&&v(c)&&(d=c,c=l);c!=l||(c=l);d!=l||(d=j);var e=H(Tb(a,b,c));d||(e=ta(e,function(a){return 0<a}));return W.o.apply(W,e)/e.length});
function Tb(a,b,c){a.c()&&h(new P("Clustering algorithms are not defined for directed graphs."));if(c!=l){var d=c;a.i()&&h(new P("Not defined for multigraphs."));r(d)||(d="weight");var e;if(0===a.q().length)c=1;else{c=a.q(j);var f=function(a){return K(a[2],d,1)};c=la(f)?R(c,function(){return f.apply(l,arguments)}):S(c);c=Math.max.apply(l,c)}e=c;c=b!=l?T(a.b(b),function(b){return[b,a.l(b)]}):V(a.adj);c=D(c,function(b){var c=b[0],f=new N(I(b[1]));f.remove(c);var g=0,B=new N;C(f,function(b){var k=K(a.l(c)[b],
d,1)/e;B.add(b);var ga=db(new N(I(a.l(b))),B);C(cb(f,ga),function(f){var F=K(a.l(b)[f],d,1)/e;f=K(a.l(c)[f],d,1)/e;g+=Math.pow(k*F*f,1/3)})});return[c,f.e(),2*g]})}else c=Sb(a,b);var g={};C(c,function(a){g[a[0]]=0===a[2]?0:a[2]/(a[1]*(a[1]-1))});return a.k(b)?H(g)[0]:g}w("jsnx.clustering",Tb);w("jsnx.transitivity",function(a){var b=0,c=0;C(Sb(a),function(a){c+=a[1]*(a[1]-1);b+=a[2]});return 0===b?0:b/c});
w("jsnx.square_clustering",function(a,b){var c=b==l?a:a.b(b),d={};C(c,function(b){var c=d[b]=0;C(Ab(I(a.l(b))),function(g){var k=g[0];g=g[1];var p=cb(new N(I(a.l(k))),I(a.l(g)));p.remove(b);p=p.e();d[b]+=p;var F=p+1,u=a.l(k);g in u&&(F+=1);c+=(G(a.l(k))-F)*(G(a.l(g))-F)+p});0<c&&(d[b]/=c)});return a.k(b)?H(d)[0]:d});function Ub(a){var b=-1,c={},d=new N;C(a.p(),function(a){var e=new N(I(a[1]));e.remove(a[0]);var f=e.e();f>b?(c[a[0]]=d=e,b=f):c[a[0]]=e});var e=new N(I(c)),f=db(e,d),g=new N,k=[],p=[];a=new A;a.next=function(){0===f.e()&&0===k.length&&h(z);var a,u;if(0<f.e())a=Ma(f),f.remove(a);else{var B=k.pop();e=B[0];g=B[1];f=B[2];p.pop();return this.next()}p.push(a);e.remove(a);g.add(a);var ka=c[a],B=cb(e,ka),ka=cb(g,ka);if(0===B.e()&&(0===ka.e()&&(u=wa(p)),p.pop(),u))return u;if(0===ka.e()&&1===B.e())return u=
va(p,B.A()),p.pop(),u;var Ca=B.e(),ga=-1,Ga,ja;for(u=Ea(ka);(a=Ma(u,l))!==l&&!(a=cb(B,c[a]),ja=a.e(),ja>ga&&(Ga=a,ga=ja,ga===Ca)););if(ga===Ca)return p.pop(),this.next();b=-1;for(u=Ea(B);(a=Ma(u,l))!==l&&!(a=cb(B,c[a]),ja=a.e(),ja>b&&(d=a,b=ja,b===Ca-1)););ga>b&&(d=Ga);k.push([e,g,f]);e=B;g=ka;f=db(e,d);return this.next()};return a}w("jsnx.find_cliques",Ub);
w("jsnx.find_cliques_recursive",function(a){var b={};C(a.p(),function(a){var c=new N(I(a[1]));c.remove(a[0]);b[a[0]]=c});a:{for(var c in b){a=m;break a}a=j}if(a)return[];a=new N(I(b));c=new N;var d=[];Vb(b,a,c,[],d);return d});
function Vb(a,b,c,d,e){var f=-1,g=b.e(),k,p,F,u;for(p=Ea(c);(F=Ma(p,l))!==l;)if(F=cb(b,a[F]),u=F.e(),u>f&&(k=F,f=u,u===g))return;C(b,function(c){c=cb(b,a[c]);var d=c.e();d>f&&(k=c,f=d)});g=db(b,k);C(g,function(f){b.remove(f);d.push(f);var g=a[f];f=cb(b,g);g=cb(c,g);f.N()&&g.N()?e.push(wa(d)):g.N()&&1===f.e()?e.push(va(d,f.A())):Vb(a,f,g,d,e);c.add(d.pop())})}w("jsnx.graph_clique_number",function(a,b){b!=l||(b=Ub(a));var c=0;Q(b,function(a){c=a.length>c?a.length:c});return c});
w("jsnx.graph_number_of_cliques",function(a,b){b!=l||(b=Ub(a));return S(b).length});function Wb(a,b,c){c!=l||(c=La(Ub(a)));b!=l||(b=a.nodes());var d;if(ha(b))d={},sa(b,function(a){d[a]=ta(c,function(b){return 0<=ra(b,a)||0<=ra(b,a+"")}).length});else{var e=b;d=ta(c,function(a){return 0<=ra(a,e)||0<=ra(a,e+"")}).length}return d}w("jsnx.number_of_cliques",Wb);function Xb(a,b){if(a.v()!=b.v())return m;var c=a.m(),d=Rb(a),e=Wb(a),f=[],g;for(g in c)f.push([c[g],d[g],e[g]]);f.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});var c=b.m(),d=Rb(b),e=Wb(b),k=[];for(g in c)k.push([c[g],d[g],e[g]]);k.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});return!za(f,k,function(a,b){return za(a,b)})?m:j}w("jsnx.algorithms.isomorphism.could_be_isomorphic",Xb);w("jsnx.could_be_isomorphic",Xb);
function Yb(a,b){if(a.v()!=b.v())return m;var c=a.m(),d=Rb(a),e=[],f;for(f in c)e.push([c[f],d[f]]);e.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});var c=b.m(),d=Rb(b),g=[];for(f in c)g.push([c[f],d[f]]);g.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});return!za(e,g,function(a,b){return za(a,b)})?m:j}w("jsnx.algorithms.isomorphism.fast_could_be_isomorphic",Yb);w("jsnx.fast_could_be_isomorphic",Yb);
function Zb(a,b){if(a.v()!=b.v())return m;var c=H(a.m());c.sort();var d=H(b.m());d.sort();return!za(c,d)?m:j}w("jsnx.algorithms.isomorphism.faster_could_be_isomorphic",Zb);w("jsnx.faster_could_be_isomorphic",Zb);function $b(a,b){if("eg"===b)return ac(a);if(b==l||"hh"===b)return bc(a);h(new nb("`opt_method` must be 'eg' or 'hh'"))}w("jsnx.is_valid_degree_sequence",$b);function bc(a){if(0===a.length)return j;if(!Pa(a)||0>Math.min.apply(l,a)||0!==W.o.apply(l,a)%2)return m;for(a=wa(a);0<a.length;){x.sort.call(a,Ba);if(0>a[0])break;var b=a.pop();if(0===b)return j;if(b>a.length)break;for(var c=a.length-1,b=a.length-(b+1);c>b;c--)a[c]-=1}return m}w("jsnx.is_valid_degree_sequence_havel_hakimi",bc);
function ac(a){if(0===a.length)return j;if(!Pa(a)||0>Math.min.apply(l,a)||0!==W.o.apply(l,a)%2)return m;var b=a.length,c=wa(a).sort(function(a,b){return b-a}),d=[],e;e=1;for(a=c.length;e<a;e++)c[e]<c[e-1]&&d.push(e);var f,g;e=0;for(a=d.length;e<a;e++)if(f=W.o.apply(l,c.slice(0,d[e])),g=d[e]*(d[e]-1)+W.o.apply(l,La(D(zb(d[e],b),function(a){return Math.min(d[e],c[a])}))),f>g)return m;return j}w("jsnx.is_valid_degree_sequence_erdos_gallai",ac);var cc,dc=l,ec="add_node add_nodes_from add_edge add_edges_from remove_node remove_nodes_from remove_edge remove_edges_from clear".split(" ");
w("jsnx.draw",function(a,b,c){function d(){L.attr("transform",function(a){return["translate(",a.x,",",a.y,")scale(",da,")"].join("")});Cb()}v(b)&&(c=b,b=l);b=b||dc||{};var e=b.d3||window.d3,f={};Db(f,mc,b);dc=b;e||h(Error("D3 requried for draw()"));f.element==l&&cc==l&&h(Error("Output element required for draw()"));cc=K(f,"element",cc);e.select(cc).select("svg.jsnx").remove();var g=e.select(cc),k=g.append("svg").classed("jsnx",j).attr("pointer-events","all"),p=k.append("g");b=p.append("g").classed("edges",
j).selectAll("g.edge");var F=p.append("g").classed("nodes",j).selectAll("g.node"),u=e.layout.force(),B=f.width||parseInt(g.style("width"),10),ka=f.height||parseInt(g.style("height"),10),Ca=f.layout_attr,g=f.nodelist||l,ga,Ga,ja,fc=a.c(),Qa=f.weighted,L=F,O=b;if(f.with_labels){var xa=f.labels;ga="object"===q(xa)?function(a){return K(xa,a.node,"")}:la(xa)?xa:t(xa)?function(a){return a.data[xa]}:function(a){return a.node}}f.labels=ga;if(Qa){var Ha=f.weights;ja="object"===q(Ha)?function(a){return K(Ha,
a.node,1)}:la(Ha)?Ha:t(Ha)?function(a){return K(a.data,Ha,1)}:ba(1)}if(f.with_edge_labels){var Ia=f.edge_labels;Ga=Qa&&!r(Ia)?ja:"object"===q(Ia)?function(a){return K(xa,a.node,"")}:la(Ia)?Ia:t(Ia)?function(a){return a.data[Ia]}:function(a){return a.edge};f.edge_labels=Ga}if(Qa&&f.weighted_stroke){var Qa=Fa(a.d(j),function(a,b){b=ja({data:b[2]});return a>b?a:b},0),Cc=e.scale.linear().range([1,f.edge_style["stroke-width"]]).domain([0,Qa]);f.edge_style["stroke-width"]=function(a){return Cc(ja.call(this,
a))}}k.select("svg.jsnx").remove();k.attr("width",B+"px").attr("height",ka+"px").style("opacity",1E-6).transition().duration(1E3).style("opacity",1);var Dc={size:j,nodes:j,links:j,start:j};Q(Ca,function(a){if(!(a in Dc))u[a](Ca[a])});u.nodes([]).links([]).size([B,ka]);var Ra=1,da=1;if(f.pan_zoom.enabled){var gc=f.pan_zoom.scale,Ja=f.edge_style["stroke-width"];la(Ja)?f.edge_style["stroke-width"]=function(){var a=Ja.apply(this,arguments);return da*(+a||parseInt(a,10))}:(Ja=+Ja||parseInt(Ja,10),f.edge_style["stroke-width"]=
function(){return da*Ja});var gb=m,hc=1,ic=Ra;k.call(e.behavior.zoom().on("zoom",function(){var a=e.event.sourceEvent.shiftKey;(a=gc&&a||!(gc||a))&&!gb?(hc=e.event.scale,ic=Ra,gb=j):!a&&gb&&(gb=m);Ra=a?ic*(e.event.scale/hc):Ra;da=!a?Ra/e.event.scale:da;a=e.event.translate;p.attr("transform","translate("+a[0]+","+a[1]+")scale("+e.event.scale+")");p.selectAll("g.edge > .line").style("stroke-width",f.edge_style["stroke-width"]);d()}))}var Cb=ea;if(fc){k.append("defs").append("marker").attr("id","Triangle").attr("markerUnits",
"strokeWidth").attr("refX","7").attr("refY","5").attr("viewBox","0 0 10 10").attr("orient","auto").append("path").attr("d","M 0 0 L 10 5 L 0 10 z");f.edge_attr["marker-end"]="url(#Triangle)";f.edge_style.fill="none";var hb=f.layout_attr.linkDistance,Sa=f.edge_offset;la(hb)||(hb=function(){return f.layout_attr.linkDistance});ha(Sa)&&(Sa=function(){return f.edge_offset});ia(Sa)&&(Sa=function(){return[f.edge_offset,f.edge_offset]});Cb=function(){O.each(function(a){if(a.source!==a.target){var b=e.select(this),
c=a.source.x,d=a.source.y,f=a.target.x,g=a.target.y,k=W.ea(c,d,f,g),f=Math.sqrt(Math.pow(f-c,2)+Math.pow(g-d,2)),g=Sa(a),g=[g[0]*da,g[1]*da];b.attr("transform",["translate(",c,",",d,")rotate(",k,")"].join(""));if(c=a.G.B(a.target.node,a.source.node)){var d=hb(a)/3,k=-d/(f/2),p=k*f;b.select(".line").attr("d",["M",g[0],k*g[0],"Q",f/2,-d,f-g[1],-k*(f-g[1])+p].join(" "))}else b.select(".line").attr("d",["M",g[0],"0 L",f-g[1],0].join(" "));g=1/da;b.select("text").attr("x",f*g/2).attr("y",c?g*(-hb(a)/4):
0).attr("transform","scale("+da+")")}})}}else Cb=function(){O.each(function(a){if(a.source!==a.target){var b=e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,k=a.target.y;a=W.ea(c,d,g,k);g=Math.sqrt(Math.pow(g-c,2)+Math.pow(k-d,2));k=g/2;b.attr("transform",["translate(",c,",",d,")rotate(",a,")"].join(""));b.select(".line").attr("d",["M 0 0 L",g,"0"].join(" "));f.with_edge_labels&&b.select("text").attr("x",k*(1/da)).attr("y",0).attr("transform","scale("+da+")"+(90<a&&279>a?"rotate(180,"+k*(1/
da)+",0)":""))}})};u.on("tick",d);k=a.H();B=a.d();g&&(c=m,k=a.b(g),B=a.d(g));L=nc(a,k,u,F,f.node_shape,ga);O=oc(a,B,u,b,Ga);pc(L,{attr:f.node_attr,style:f.node_style,P:f.label_style,O:f.label_attr},f.with_labels);qc(O,{attr:f.edge_attr,style:f.edge_style,P:f.edge_label_style,O:f.edge_label_attr},f.with_edge_labels,l,fc);if(c){rc(a,m);var oa=a.constructor.prototype,ib=f.node_shape,jb={attr:f.node_attr,style:f.node_style,O:f.label_attr,P:f.label_style},jc={attr:f.edge_attr,style:f.edge_style,O:f.edge_label_attr,
P:f.edge_label_style},kb=f.labels,kc=f.edge_labels,lb=f.with_labels,lc=f.with_edge_labels,Ec=a.c();a.add_node=a.F=function(a){var b=!this.k(a);oa.add_node.apply(this,arguments);b&&(L=nc(this,[a],u,L,ib,kb));pc(L,jb,lb,[a]);u.start()};a.add_nodes_from=a.h=function(a){var b=ta(S(a),function(a){return!this.k(s(a)?a[0]:a)},this);oa.add_nodes_from.apply(this,arguments);0<b.length&&(L=nc(this,b,u,L,ib,kb));pc(L,jb,lb,a);u.start()};a.add_edge=a.g=function(b,c){var d=!this.B(b,c),e=[];d&&(e=ta(b==c?[b]:[b,
c],function(a){return!this.k(a)},this));oa.add_edge.apply(a,arguments);0<e.length&&(L=nc(this,e,u,L,ib,kb),pc(L,jb,lb,e));d&&(O=oc(this,[[b,c]],u,O,kc));qc(O,jc,lc,[[b,c]],Ec);u.start()};a.add_edges_from=a.a=function(b){var c=[],d=[],e={},f={},g=this.c();Q(b,function(a){var b=a[0];a=a[1];if(!this.B(b,a)&&!([b,a]in e)&&(g||!([a,b]in e)))c.push([b,a]),e[[b,a]]=j,!this.k(b)&&!(b in f)&&(d.push(b),f[b]=j),!this.k(a)&&!(a in f)&&(d.push(a),f[a]=j)},this);oa.add_edges_from.apply(a,arguments);0<d.length&&
(L=nc(this,d,u,L,ib,kb),pc(L,jb,lb,d));0<c.length&&(O=oc(this,c,u,O,kc));qc(O,jc,lc,c,g);u.start()};a.remove_node=a.J=function(b){try{if(this.k(b)){L=sc(this,[b],u,L);var c=this.d([b]);this.c()&&(c=Ka(c,this.C([b])));O=tc(this,c,u,O);u.resume()}}catch(d){}oa.remove_node.apply(a,arguments)};a.remove_nodes_from=a.T=function(b){try{L=sc(this,b,u,L);var c=this.d(b);this.c()&&(c=Ka(c,this.C(b)));O=tc(this,c,u,O);u.resume()}catch(d){}oa.remove_nodes_from.apply(a,arguments)};a.remove_edge=a.s=function(b,
c){try{O=tc(this,[[b,c]],u,O),u.resume()}catch(d){}oa.remove_edge.apply(a,arguments)};a.remove_edges_from=a.w=function(b){try{O=tc(this,b,u,O),u.resume()}catch(c){}oa.remove_edges_from.apply(a,arguments)};a.clear=a.clear=function(){L=L.data([],uc);L.exit().remove();O=O.data([],vc);O.exit().remove();u.nodes([]).links([]).resume();oa.clear.apply(a,arguments)};a.bound=j}else a.bound?rc(a):wc(a);u.start();return u});
function nc(a,b,c,d,e,f){var g=c.nodes();Q(b,function(b){var c=a.node[b];b={node:b,data:c,G:a};g.push(b);c.__d3datum__=b});d=d.data(g,uc);b=d.enter().append("g").classed("node",j).call(c.drag);b.append(e).classed("node-shape",j);f&&b.append("text").text(f);return d}
function oc(a,b,c,d,e){var f=c.links();Q(b,function(b){var c=b[0],d=b[1];b=b[2]||a.K(c,d);c={edge:[c,d],redge:[d,c],source:a.node[c].__d3datum__,target:a.node[d].__d3datum__,data:b,G:a};f.push(c);b.__d3datum__=c});d=d.data(f,vc);b=d.enter().append("g").classed("edge",j);b.append("path").classed("line",j);e&&b.append("text").text(e);return d}
function pc(a,b,c,d){if(d!=l){var e={};Q(d,function(a){e[s(a)?a[0]:a]=j});a=a.filter(function(a){return a.node in e})}var f=a.selectAll(".node-shape");E(b.attr,function(a,b){f.attr(b,a)});E(b.style,function(a,b){f.style(b,a)});if(c){var g=a.selectAll("text");E(b.O,function(a,b){g.attr(b,a)});E(b.P,function(a,b){g.style(b,a)})}}
function qc(a,b,c,d,e){if(d!=l){var f={};Q(d,function(a){f[[a[0],a[1]]]=j});a=a.filter(function(a){return a.edge in f||e||a.redge in f})}var g=a.selectAll(".line");E(b.attr,function(a,b){g.attr(b,a)});E(b.style,function(a,b){g.style(b,a)});if(c){var k=a.selectAll("text");E(b.O,function(a,b){k.attr(b,a)});E(b.P,function(a,b){k.style(b,a)})}}function uc(a){return a.node}function vc(a){return a.edge}
function sc(a,b,c,d){var e=c.nodes();Q(a.b(b),function(b){ua(e,a.node[b].__d3datum__)});d=d.data(e,uc);d.exit().remove();return d}function tc(a,b,c,d){var e=c.links();Q(b,function(b){ua(e,K(a.K(b[0],b[1],{}),"__d3datum__",l))});d=d.data(e,vc);d.exit().remove();return d}w("jsnx.is_bound",function(a){return a.bound});function rc(a,b){if(a.bound){var c=a.constructor.prototype;sa(ec,function(b){a[b]=c[b]});delete a.bound;(!r(b)||b)&&wc(a)}}w("jsnx.unbind",rc);
function wc(a){Q(a.H(j),function(a){J(a[1],"__d3datum__")});Q(a.d(j),function(a){J(a[2],"__d3datum__")})}
var mc={layout_attr:{charge:-120,linkDistance:40},node_shape:"circle",node_attr:{r:10},node_style:{stroke:"#333",fill:"#999",cursor:"pointer"},edge_attr:{},edge_style:{stroke:"#000","stroke-width":2},label_attr:{},label_style:{"text-anchor":"middle","dominant-baseline":"central",cursor:"pointer","-webkit-user-select":"none",fill:"#000"},edge_label_attr:{},edge_label_style:{"font-size":"0.8em","dominant-baseline":"central","text-anchor":"middle","-webkit-user-select":"none"},with_labels:m,with_edge_labels:m,
edge_offset:10,weighted:m,weights:"weight",weighted_stroke:j,pan_zoom:{enabled:j,scale:j}};function xc(a,b){var c=yc(a,b);c.name("complete_graph("+a+")");1<a&&c.a(c.c()?Bb(zb(a)):Ab(zb(a)));return c}w("jsnx.complete_graph",xc);w("jsnx.cycle_graph",function(a,b){var c=zc(a,b);c.name("cycle_graph("+a+")");1<a&&c.g(a-1,0);return c});function yc(a,b){a instanceof X&&(b=a,a=l);a!=l||(a=0);var c;b!=l?(c=b,c.clear()):c=new X;c.h(zb(a));c.name("empty_graph("+a+")");return c}w("jsnx.empty_graph",yc);w("jsnx.null_graph",function(a){a=yc(0,a);a.name("null_graph()");return a});
function zc(a,b){var c=yc(a,b);c.name("path_graph("+a+")");c.a(D(zb(a-1),function(a){return[a,a+1]}));return c}w("jsnx.path_graph",zc);w("jsnx.trivial_graph",function(a){a=yc(1,a);a.name("null_graph()");return a});w("jsnx.fast_gnp_random_graph",function(a,b,c){c!=l||(c=m);var d=yc(a);d.name("fast_gnp_random_graph("+a+","+b+")");if(0>=b||1<=b)return Ac(a,b,c);var e=1,f=-1;b=Math.log(1-b);if(c)for(d=Y(d);e<a;){c=Math.log(1-Math.random());f=f+1+Math.floor(c/b);for(e===f&&(f+=1);f>=a&&e<a;)f-=a,e+=1,e==f&&(f+=1);e<a&&d.g(e,f)}else for(;e<a;){c=Math.log(1-Math.random());for(f=f+1+Math.floor(c/b);f>=e&&e<a;)f-=e,e+=1;e<a&&d.g(e,f)}return d});
function Ac(a,b,c){var d;d=c?Y():X();d.h(zb(a));d.name("gnp_random_graph("+a+","+b+")");if(0>=b)return d;if(1<=b)return xc(a,d);a=d.c()?Bb(zb(a)):Ab(zb(a));C(a,function(a){Math.random()<b&&d.g(a[0],a[1])});return d}w("jsnx.gnp_random_graph",Ac);w("jsnx.binomial_graph",Ac);w("jsnx.erdos_renyi_graph",Ac);w("jsnx.havel_hakimi_graph",function(a,b){$b(a)||h(new P("Invalid degree sequence"));b!=l&&(b.c()&&h(new P("Directed Graph not supported")),b.i()&&h(new P("Havel-Hakimi requires simple graph")));var c=a.length,d=yc(c,b);if(0===c||0===Math.max.apply(l,a))return d;for(c=La(D(d,function(b){return[a[b],b]}));0<c.length;){c.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:+a[1]-+b[1]});if(0>c[0][0])return m;var e=c.pop();if(0===e[0])break;if(e[0]>c.length)return m;for(var f=c.length,g=f-e[0];g<f;g++)d.g(e[1],
c[g][1]),c[g][0]-=1}d.name("havel_hakimi_graph "+d.v()+" nodes "+d.size()+" edges");return d});function Bc(a,b,c){var d=b;la(b)&&(d={},C(a.H(),function(a){d[a]=b(a)}));var e;if(!r(c)||c){var f=d,g=new a.constructor;g.name("("+a.name()+")");a.i()?g.a(D(a.d(j,j),function(a){return[K(f,a[0],a[0]),K(f,a[1],a[1]),a[2],Wa(a[3])]})):g.a(D(a.d(j),function(a){return[K(f,a[0],a[0]),K(f,a[1],a[1]),Wa(a[2])]}));g.h(D(a,function(a){return K(f,a,a)}));c={};for(e in a.node)c[K(f,e,e)]=Wa(a.node[e]);M(g.node,c);M(g.graph,Wa(a.graph));e=g}else{var k=d;e=new N(I(k));if(0<cb(e,k).e()){e=Y(Eb(k));e.w(e.U());try{g=
Qb.Ma.$a(e)}catch(p){p instanceof qb&&h(new qb("The node label sets are overlapping and no ordering can resolve the mapping. Use copy=True."))}g.reverse()}else g=e;var F=a.i(),u=a.c(),B;C(g,function(b){var c;b in k&&(c=k[b],a.k(b)||h(new P("Node "+b+" is not in the graph.")),a.F(c,a.node[b]),F?(B=y(a.q(b,j,j),function(a){return[c,a[1],a[2],a[3]]}),u&&(B=va(B,y(a.M(b,j,j),function(a){return[a[0],c,a[2],a[3]]})))):(B=y(a.q(b,j),function(a){return[c,a[1],a[2]]}),u&&(B=va(B,y(a.M(b,j),function(a){return[a[0],
c,a[2]]})))),a.J(b),a.a(B))});e=a}return e}w("jsnx.relabel_nodes",Bc);
w("jsnx.convert_node_labels_to_integers",function(a,b,c,d){3===arguments.length&&v(c)?(d=c,c=l):2===arguments.length&&(v(b)?(d=b,b=l):t(b)&&(c=b,b=l));b!=l||(b=0);c!=l||(c="default");d!=l||(d=j);var e={},f,g,k,p;if("default"===c){f=a.nodes();g=0;k=b;for(p=f.length;g<p;g++,k++)e[f[g]]=k}else if("sorted"===c){f=a.nodes();f.sort();g=0;k=b;for(p=f.length;g<p;g++,k++)e[f[g]]=k}else if("increasing degree"===c){f=La(a.n());f.sort(function(a,b){return a[1]-b[1]});g=0;k=b;for(p=f.length;g<p;g++,k++)e[f[g][0]]=
k}else if("decreasing degree"===c){f=La(a.n());f.sort(function(a,b){return b[1]-a[1]});g=0;k=b;for(p=f.length;g<p;g++,k++)e[f[g][0]]=k}else h(new P("Unkown node ordering: "+c));g=Bc(a,e);g.name("("+a.name()+")_with_int_labels");d||(g.node_labels=e);return g});}());
